site = {
    "name": "Max Sepúlveda",
    "title_suffix": "Portfolio",
    "description": "Portfolio profesional de Max Sepúlveda, artista visual, artesano y gestor cultural chileno. Más de 20 años de trayectoria en arte colaborativo, cerámica y textiles.",
    "tagline": "Artista visual · Artesano · Gestor cultural",
    "email": "maxsepulvedaz@gmail.com",
    "phone": "+56 9 8654 5810",
    "phone_link": "+56986545810",
    "location": "San Vicente de Tagua Tagua, Chile",
    "year": "2026",
    "website": "https://maxsepulvedaartevisual.com",
    "instagram": "https://www.instagram.com/maxartepopular/",
    "facebook": "https://www.facebook.com/MaxArteVisual/",
    "youtube": "https://www.youtube.com/@Warisdey1974",
}


def gallery(folder: str, names: list[str]) -> list[str]:
    return [f"assets/images/gallery/{folder}/{name}" for name in names]

disciplines = [
    {
        "name": "Alfarería",
        "description": "Creación de piezas utilitarias y decorativas con técnicas y diseños ancestrales.",
        "icon": "pottery",
        "image": "assets/images/disciplinas/alfareria.jpg",
        "anchor": "alfareria",
        "panel": "fullbleed",
    },
    {
        "name": "Cerámica",
        "description": "Técnica de moldes, modelado, esgrafiado, uso de engobes y vidriados. Exploración de formas tradicionales con una mirada contemporánea.",
        "icon": "ceramic",
        "image": "assets/images/disciplinas/ceramica.jpeg",
        "anchor": "ceramica",
        "panel": "plate",
    },
    {
        "name": "Bordado",
        "description": "Exploración con puntadas tradicionales, mapas textiles colectivos y procesos comunitarios de memoria.",
        "icon": "embroidery",
        "image": "assets/images/disciplinas/bordado.jpg",
        "anchor": "bordado",
        "panel": "fullbleed",
    },
    {
        "name": "Batik y bordado",
        "description": "Fusión contemporánea de batik y bordado para poner en valor el patrimonio natural y cultural.",
        "icon": "batik",
        "image": "assets/images/disciplinas/batik-y-bordado.jpg",
        "anchor": "batik-y-bordado",
        "panel": "fullbleed",
    },
    {
        "name": "Tejidos",
        "description": "Telar mapuche, telar de peine, telar cuadrado, telar artístico, cordonería andina y joyería textil.",
        "icon": "weaving",
        "image": "assets/images/disciplinas/tejidos.jpg",
        "anchor": "tejidos",
        "panel": "fullbleed",
    },
    {
        "name": "Técnicas de teñido por reserva",
        "description": "Batik, pintura en seda y teñido por amarras. Diseños precolombinos y contemporáneos.",
        "icon": "batik",
        "image": "assets/images/disciplinas/tecnicas-de-tenido-por-reserva.jpeg",
        "anchor": "tecnicas-de-tenido-por-reserva",
        "panel": "plate",
    },
    {
        "name": "Audiovisuales",
        "description": "Dirección de arte y realización de documentales que registran y difunden procesos creativos comunitarios.",
        "icon": "video",
        "image": "assets/images/disciplinas/audiovisuales.jpeg",
        "anchor": "audiovisuales",
        "panel": "plate",
    },
    {
        "name": "Arte colaborativo",
        "description": "Bordados de mapas de la memoria, murales textiles, pasacalles e intervenciones artísticas en el paisaje natural y cultural.",
        "icon": "embroidery",
        "image": "assets/images/disciplinas/arte-colaborativo.jpg",
        "anchor": "arte-colaborativo",
        "panel": "fullbleed",
    },
]

milestones = [
    {
        "year": "2025",
        "title": "Exposición Alfarería Ancestral",
        "description": "Exposición individual de alfarería en el Museo Escolar Laguna de Tagua Tagua y co-autoría en el libro histórico y patrimonial sobre la cuenca del río Tinguiririca.",
    },
    {
        "year": "2024",
        "title": "Gestión Cultural y Práctica en México",
        "description": "Se titula de Técnico de Nivel Superior en Arte y Gestión Cultural y realiza talleres y co-creaciones de murales textiles colaborativos en Oaxaca y Morelos, México.",
    },
    {
        "year": "2023",
        "title": "Bordado Atacameño de la Memoria",
        "description": "Dirección e impartición del taller de bordado tradicional y exposición colectiva en San Pedro de Atacama y Santiago en colaboración con la comunidad y SQM.",
    },
    {
        "year": "2022",
        "title": "Reconocimiento Regional O'Higgins",
        "description": "Homenaje por su aporte al desarrollo cultural local en el marco del Día del Artesano. Más de 25 años dedicados al arte colaborativo y la gestión cultural.",
    },
    {
        "year": "2021",
        "title": "Catálogo Artesanía en Pandemia",
        "description": "Seleccionado nacional para el catálogo del Ministerio de las Culturas que reconoce a artesanos con destacada trayectoria y oficio durante la emergencia sanitaria.",
    },
    {
        "year": "2020",
        "title": "Mediación Artística Digital",
        "description": "Adapta su labor al formato virtual durante la pandemia. Cápsulas de formación en bordado y arpillera para comunidades, reconociendo buenas prácticas de mediación.",
    },
    {
        "year": "2019",
        "title": "Costa Rica Fashion Week",
        "description": "Presenta creaciones de moda textil con identidad chilena en la semana de la moda de Costa Rica, integrando artesanía tradicional en el diseño contemporáneo.",
    },
    {
        "year": "2018",
        "title": "Residencia y Exposición — Nueva Zelanda",
        "description": "Exposición individual 'Textiles y Alfarería del Tagua Tagua' en la School of Art de Dunedin. Intercambio cultural con la tradición maorí.",
    },
    {
        "year": "2016",
        "title": "Residencia Red Cultura — Alicahue",
        "description": "Residencia de arte colaborativo en el Valle de Alicahue, Región de Valparaíso. Trabajo con comunidades locales en intervenciones artísticas territoriales.",
    },
    {
        "year": "2016",
        "title": "Bordado Charrúa de la Memoria",
        "description": "Ganador de los Fondos Concursables para la Cultura del MEC uruguayo. Mapa textil colectivo de la costa de Rocha, Uruguay.",
    },
    {
        "year": "2012",
        "title": "Bordado Urbano — Calama",
        "description": "Intervención de arte público colaborativo. Mapa textil de 3×2 metros bordado por más de un centenar de habitantes de Calama.",
    },
    {
        "year": "2006",
        "title": "Fondart — Widüfe Kuyfiche",
        "description": "Investigación y rescate de la alfarería indígena de la zona central de Chile. Exposición en la Sala Samuel Román de Rancagua.",
    },
    {
        "year": "2002",
        "title": "Proyecto 'Desde la Óptica Wlachinsky'",
        "description": "Participa en proyecto de creación artística en Valdivia, financiado por Fondart Regional de Los Ríos. Primer acercamiento al cruce entre artesanía y artes visuales.",
    },
]

projects = [
    {
        "title": "Bordado Urbano",
        "slug": "bordado-urbano",
        "date": "2012-05-15",
        "summary": "Proyecto de arte comunitario en Calama (2012). Los habitantes bordaron colectivamente un mapa de 3x2 metros representando sus sueños e historias.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-urbano/",
        "tags": ["Arte Comunitario", "Textil", "Calama", "Documental"],
        "image": "assets/images/proyectos/intervenciones/Mapa Bordado Atacameño.jpg",
        "gallery": gallery(
            "bordado-urbano",
            [
                "bordado-urbano-01.jpg",
                "bordado-urbano-02.jpg",
                "bordado-urbano-03.jpg",
                "bordado-urbano-04.jpg",
                "bordado-urbano-05.jpg",
                "bordado-urbano-06.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Un tapiz de sueños colectivos",
                "content": "<p>Proyecto de arte comunitario en el que los habitantes de Calama bordaron colectivamente un mapa de <strong>3 x 2 metros</strong> representando sus sueños e historias para la ciudad.</p><p>Fue una intervención pública realizada en distintas locaciones (ferias, paseos peatonales, mercados), acompañada por la filmación de un <strong>documental</strong> sobre la experiencia.</p><p>El resultado fue un tapiz urbano único, fruto del trabajo conjunto del artista con más de un centenar de participantes locales.</p>",
                "variant": "default",
            },
            {
                "type": "quote",
                "quote": "El bordado es una herramienta convocante que invita a la participación de personas de todas las edades.",
                "author": "Max Sepúlveda",
                "variant": "highlight",
            },
        ],
    },
    {
        "title": "Bordado Charrúa de la Memoria",
        "slug": "bordado-charrua-de-la-memoria",
        "date": "2016-11-20",
        "summary": "Mapa textil colectivo de la costa de Rocha, Uruguay. Ganador de los Fondos Concursables para la Cultura del MEC uruguayo (2016).",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-charrua-de-la-memoria/",
        "tags": ["Arte Comunitario", "Textil", "Uruguay", "Premios"],
        "image": "assets/images/proyectos/intervenciones/mx.jpg",
        "gallery": gallery(
            "bordado-charrua",
            [
                "bordado-charrua-01.jpg",
                "bordado-charrua-02.jpg",
                "bordado-charrua-03.jpg",
                "bordado-charrua-04.jpg",
                "bordado-charrua-05.jpg",
                "bordado-charrua-06.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Rescatando la memoria costera",
                "content": "<p>Proyecto ganador de los <strong>Fondos Concursables para la Cultura</strong> del Ministerio de Educación y Cultura de Uruguay.</p><p>Consistió en la creación de un mapa textil colectivo de la costa de Rocha, bordado in situ por habitantes y visitantes en <strong>cinco localidades costeras</strong>.</p><p>Durante el proceso, la gente compartió anécdotas sobre los lugares que dejaron huella en sus vidas: historias de amor, aventuras, desventuras —y también lo que se perdió, lo que cambiaría y lo que falta en su entorno. Sepúlveda actuó como facilitador: enseñó técnicas de bordado en el momento, de modo que incluso quienes nunca habían bordado pudieron contribuir con sus puntadas.</p><p>El proyecto culminó con la exhibición del mapa bordado y la proyección del documental en las mismas comunidades donde se gestó, así como en Montevideo y circuitos internacionales.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Textiles y Alfarería del Tagua Tagua",
        "slug": "textiles-y-alfareria-del-tagua-tagua",
        "date": "2018-08-10",
        "summary": "Exposición individual en la School of Art de Dunedin, Nueva Zelanda (2018). Diálogo entre la identidad cultural de Tagua Tagua y la tradición maorí.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/residencia-artistica-en-nueva-zelanda/",
        "tags": ["Exposición", "Internacional", "Nueva Zelanda", "Cerámica", "Textil"],
        "image": "assets/images/proyectos/alfareria/DSC05942.JPG",
        "gallery": gallery(
            "nueva-zelanda",
            [
                "nueva-zelanda-01.jpg",
                "nueva-zelanda-02.jpg",
                "nueva-zelanda-03.jpg",
                "nueva-zelanda-04.jpg",
                "nueva-zelanda-05.jpg",
                "nueva-zelanda-06.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Intercambio Cultural Chile-Nueva Zelanda",
                "content": "<p>Exposición individual realizada en la <strong>School of Art de Dunedin</strong>, como resultado de una residencia artística en Nueva Zelanda.</p><p>La muestra presentó una selección de obras en cerámica y textil inspiradas en la identidad cultural de <strong>Tagua Tagua</strong> y su diálogo con la tradición maorí.</p><p>Como parte de la residencia, Sepúlveda ofreció un <strong>taller de alfarería ancestral</strong> en el estudio de cerámica de la escuela, compartiendo técnicas tradicionales chilenas con estudiantes neozelandeses. El intercambio enriqueció su práctica, incorporando influencias del arte oceánico.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Widüfe Kuyfiche – Alfarero Ancestral",
        "slug": "widufe-kuyfiche-alfarero-ancestral",
        "date": "2006-03-01",
        "summary": "Investigación y rescate de la alfarería indígena de la zona central de Chile. Proyecto FONDART 2006.",
        "featured": True,
        "tags": ["Investigación", "Cerámica", "Fondart", "Patrimonio"],
        "image": "assets/images/proyectos/alfareria/DSC05935.JPG",
        "gallery": gallery(
            "ceramica",
            [
                "ceramica-01.jpg",
                "ceramica-02.jpg",
                "ceramica-03.jpg",
                "ceramica-04.jpg",
                "ceramica-05.jpg",
                "ceramica-06.jpg",
                "ceramica-07.jpg",
                "ceramica-08.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Hacedores de Greda",
                "content": "<p>Proyecto financiado por el <strong>Fondo Nacional de Desarrollo Cultural y las Artes (FONDART)</strong>.</p><p>Consistió en una investigación y rescate de la alfarería indígena de la zona central de Chile, que culminó en una exposición exhibida en la <strong>Sala Samuel Román</strong> de la Casa de la Cultura de Rancagua. La muestra presentó piezas de cerámica inspiradas en técnicas prehispánicas, poniendo en valor el oficio del alfarero tradicional.</p><p><em>Widüfe</em> en mapudungun significa 'alfarero' o 'hacedor de greda'. Fue un hito temprano en la carrera de Sepúlveda, consolidando su vínculo con el patrimonio de la zona central de Chile.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Murales Textiles Colaborativos",
        "slug": "murales-textiles-colaborativos",
        "date": "2020-01-15",
        "summary": "Serie de intervenciones colaborativas en que comunidades crean murales de telas y bordados para espacios públicos. Incluye el mural 'Inti Ray' en Calama, financiado por Codelco.",
        "featured": True,
        "tags": ["Arte Comunitario", "Textil", "Muralismo", "Codelco"],
        "image": "assets/images/proyectos/intervenciones/20240703_201741.jpg",
        "gallery": gallery(
            "murales",
            [
                "mural-01.jpg",
                "mural-02.jpg",
                "mural-03.jpg",
                "mural-04.jpg",
                "mural-05.jpg",
                "mural-06.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Mosaicos Comunitarios",
                "content": "<p>Diversas intervenciones lideradas por Sepúlveda donde comunidades completas crean <strong>murales hechos de telas y bordados</strong> que se instalan en espacios públicos locales a modo de mosaico comunitario.</p><p>Un ejemplo destacado es el mural <strong>'Inti Ray'</strong> en Calama, resultado del proyecto <em>Rescate del Patrimonio e Identidad Cultural Textil de los Pobladores de la Inti Ray</em>, financiado por <strong>Codelco</strong> dentro del programa Calama Participa. La obra fue conformada por múltiples paños bordados o tejidos por diferentes manos, representando símbolos y relatos de la comunidad.</p><p>Estas obras colectivas se han realizado en poblados rurales y barrios urbanos de distintas regiones, fortaleciendo el sentido de identidad y pertenencia de sus autores colectivos.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Residencia Artística Alicahue",
        "slug": "residencia-artistica-alicahue",
        "date": "2016-10-01",
        "summary": "Residencia del programa Red Cultura en la Región de Valparaíso (2016), trabajando con comunidades locales.",
        "featured": True,
        "tags": ["Arte Comunitario", "Residencia", "Valparaíso", "Red Cultura"],
        "image": "assets/images/proyectos/general/foto residencia.jpg",
        "gallery": [
            "assets/images/proyectos/general/foto residencia.jpg",
            "assets/images/proyectos/general/20160109_170617.jpg",
            "assets/images/proyectos/general/IMG-20151119-WA0000.jpeg",
        ],
        "content": [
            {
                "type": "text_section",
                "title": "Arte colaborativo en el Valle de Alicahue",
                "content": "<p>Seleccionado por el programa <strong>Red Cultura</strong> del Ministerio de las Culturas para una residencia de arte colaborativo en el <strong>Valle de Alicahue</strong>, Región de Valparaíso.</p><p>Durante la residencia, Sepúlveda trabajó junto a comunidades locales en intervenciones artísticas que partieron de la reflexión sobre el territorio, la memoria y la identidad del valle. El proceso buscó dejar capacidades instaladas y visibilizar el patrimonio cultural de la zona a través de la co-creación.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Costa Rica Fashion Week 2019",
        "slug": "costa-rica-fashion-week-2019",
        "date": "2019-08-01",
        "summary": "Participación internacional con textiles, ponchos y piezas de diseño de autor en Costa Rica Fashion Week 2019.",
        "featured": True,
        "tags": ["Textil", "Moda", "Internacional", "Costa Rica"],
        "image": "assets/images/proyectos/general/stand CRFW.jpg",
        "gallery": gallery(
            "costa-rica-fashion-week",
            [
                "costa-rica-fashion-week-01.jpg",
                "costa-rica-fashion-week-02.jpg",
                "costa-rica-fashion-week-03.jpg",
                "costa-rica-fashion-week-04.jpg",
                "costa-rica-fashion-week-05.jpg",
                "costa-rica-fashion-week-06.jpg",
                "costa-rica-fashion-week-07.jpg",
                "costa-rica-fashion-week-08.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Textil, oficio y diseño contemporáneo",
                "content": "<p>En 2019 Max Sepúlveda participó en <strong>Costa Rica Fashion Week</strong>, presentando piezas textiles y vestuario con identidad chilena en un contexto internacional de moda y diseño.</p><p>La participación permitió mostrar ponchos, tramas, aplicaciones textiles y accesorios de autor como una extensión contemporánea de técnicas tradicionales. El proyecto abrió un diálogo entre artesanía, diseño escénico, circulación internacional y oficio textil latinoamericano.</p><p>Esta instancia forma parte de su trayectoria internacional y de su interés por llevar los lenguajes textiles a nuevos soportes: del mural comunitario al cuerpo, de la memoria local a la pasarela.</p>",
                "variant": "default",
            },
        ],
    },
]

institutions = [
    "SQM",
    "Novandino Litio",
    "Corporación Proloa",
    "Ministerio de las Culturas, las Artes y el Patrimonio de Chile",
    "Ministerio de Educación y Cultura de Uruguay",
    "Colegio Cryptocaria Alba de Peumo",
    "Gobierno Regional de Antofagasta",
    "Fundación de Cultura de San Pedro de Atacama",
    "Museo Violeta Parra",
    "Gobierno Regional de O'Higgins",
    "Municipalidad de Santa Cruz",
    "Municipalidad de San Vicente de Tagua Tagua",
    "Ministerio de Vivienda y Urbanismo de Chile",
    "Escuela Rewe Waldorf de San Vicente de Tagua Tagua",
    "Escuela Alcaman de Doñihue",
    "Escuela de Joyería Joyarte de Valdivia",
    "Instituto de Desarrollo Agropecuario de Chile INDAP",
    "Fundación PRODEMU Pro Desarrollo de la Mujer de Chile",
    "Corporación de Cultura y Turismo de Calama",
    "Codelco Chile",
    "Centro Cultural Daniel Omar Favero y Centro de Desarrollo Sustentable Mamaroja en Argentina",
    "Agrupación Cultural Rapa Nui Maohi o Rapa Nui",
    "Servicio Nacional de la Mujer de Chile",
    "Municipalidad de Rancagua",
    "Fondo de Solidaridad e Inversión Social FOSIS Chile",
    "Casa Taller Recreo-Arte Textil en Viña del Mar",
    "Escuela Textil Factoría Violeta",
    "Municipalidad de Oberá, Argentina",
]

collaborations = [
    "Espacio Cultural Leritchitacks de San Pedro de Atacama",
    "Junta de Vigilancia del río Tinguiririca",
    "Editorial Humanos",
    "Museo Regional de Rancagua",
    "Ecositex",
    "Centro Cultural Montecarmelo",
    "Pichilemu TV",
    "Museo de la Educación Gabriela Mistral",
    "Costa Rica Fashion Week",
    "Otago Polytechnic de Nueva Zelanda",
    "Corporación Parque por la Paz de Villa Grimaldi",
    "Museo de Arte y Artesanía de Linares de Chile",
    "TVO San Vicente",
    "Centro Cultural La Moneda de Chile",
    "Instituto San Vicente",
    "Universidad Autónoma de México",
    "Instituto Chileno-Guatemalteco de Cultura",
    "Corporación de Cultura de la Municipalidad de Viña del Mar",
    "Secretaría de Cultura del Gobierno de México",
    "Corporación Unificada Nacional de Educación Superior de Colombia",
    "Ministerio de Cultura de Costa Rica",
    "Corporación Pro O'Higgins",
    "Corporación Añañuca",
    "Museo Escolar Laguna de Tagua Tagua",
    "Centro Cultural Gabriela Mistral, Santiago",
    "Agrupación Cultural Ayllu Sin Frontera de San Pedro de Atacama",
    "Tejedoras Urbanas Xico de Ciudad de México",
    "Espacio Cultural Gárgola de Santiago",
    "Casona Cultural de Pichidegua",
    "Centro Cultural Nelly Lemus de Antofagasta",
    "Corporación Cultural Municipal de Valdivia",
    "Centro de Salud Familiar de San Vicente de Tagua Tagua",
    "Museo Lircunlauta",
    "Biblioteca Pública de Chépica",
    "Teatro Municipal de Rengo",
    "Centro Cultural Agustín Ross de Pichilemu",
    "Centro Cultural de Lolol",
    "Centro Cultural de Machalí",
    "Centro Cultural de Codegua",
    "Casa de la Cultura de Rancagua",
    "Lollapalooza 2022",
    "Municipalidad de Recoleta",
    "Gobernación Provincial de Cachapoal",
    "Centro Cultural Ojo del Desierto de Calama",
    "Instituto de Investigaciones Arqueológicas y Museo de la Universidad Católica del Norte",
    "Revista Scope Contemporary Research Topics Art and Design de Nueva Zelanda",
]

awards = [
    {"year": "2021", "title": "Seleccionado nacional para el Catálogo Artesanía en Pandemia del Ministerio de las Culturas, las Artes y el Patrimonio de Chile."},
    {"year": "2015", "title": "Reconocimiento al Artesano 2015, Municipalidad de San Vicente de Tagua Tagua, Chile."},
    {"year": "2014", "title": "Reconocimiento por selección del cortometraje Bordado Urbano en el I Festival de Textiles de México, Universidad Autónoma de México."},
    {"year": "2006", "title": "Primer lugar en el III Concurso de Alfombras Guatemaltecas, Corporación de Cultura de la Municipalidad de Viña del Mar, Chile."},
]

exhibitions = [
    {"year": "2026", "title": "Exposición individual Andino, Espacio Cultural Leritchitacks de San Pedro de Atacama, Chile."},
    {"year": "2025", "title": "Exposición colectiva Alfarería Ancestral, Museo Escolar Laguna de Tagua Tagua, San Vicente de Tagua Tagua, Chile."},
    {"year": "2024", "title": "Exposición colectiva Art Santiago 2024 en el Centro Cultural Gabriela Mistral GAM, Santiago, Chile."},
    {"year": "2023", "title": "Exposición colectiva de egreso Pieza Única, Instituto Profesional AIEP, Santiago, Chile."},
    {"year": "2023", "title": "Exposición colectiva Bordado Atacameño de la Memoria, San Pedro de Atacama y Edificio Corporativo SQM, Santiago, Chile."},
    {"year": "2023", "title": "Exposición colectiva Memorias de la Artesanía, UNAR, Museo Regional de Rancagua y Museo de Artes Decorativas, Santiago, Chile."},
    {"year": "2022", "title": "Exposición colectiva Artesanías para Violeta, UNAR, Sala Nemesio Antúnez UMCE, Santiago, Chile."},
    {"year": "2021", "title": "Exposición colectiva Artesanía en Pandemia, una Pieza Para el Sello de Excelencia, UNAR, Centro Cultural Montecarmelo, Santiago, Chile."},
    {"year": "2018", "title": "Exposición individual Textiles y Alfarería del Tagua Tagua, Escuela de Arte de Dunedin, Otago Polytechnic, Nueva Zelanda."},
    {"year": "2016-2018", "title": "Exposición individual Widufe Kuyfiche - Alfarero Ancestral, itinerancia por centros culturales de la Región de O'Higgins."},
    {"year": "2015", "title": "Exposición colectiva II Feria de Artesanías Iberoamericanas, Centro Cultural Palacio de la Moneda, Santiago, Chile."},
    {"year": "2015", "title": "Exposición colectiva Expo Cachapoal, Plaza de los Héroes de Rancagua, Copa América 2015, Chile."},
    {"year": "2012", "title": "Exposición individual Retrospectiva, Hall del Edificio de CODELCO, Calama, Chile."},
    {"year": "2012", "title": "Exposición colectiva Ckoitchi, Sala de Arte Pablo Neruda de Calama, Chile."},
    {"year": "2011", "title": "Exposición colectiva Ponle Color al Invierno, Corporación Cultural Municipal de Valparaíso, Chile."},
    {"year": "2010", "title": "Exposición colectiva El Litoral Vive, Oberá, Puerto Rico y Posadas, Misiones, Argentina."},
    {"year": "2008", "title": "Exposición individual Entre Chile y México, Sala de Arte Contemporáneo de la Casa de la Cultura de Rancagua, Chile."},
    {"year": "2006", "title": "Exposición individual Arte Rupestre Regional en Tapices de Batik y Shibori, Rancagua, San Fernando y Pichilemu, Chile."},
    {"year": "2005", "title": "Exposición individual Reservando el Color, Gobernación Provincial de Cachapoal, Rancagua, Chile."},
    {"year": "2002", "title": "Exposición colectiva Petroglifos del Río Cipreses y El Hombre, SITIARTE, Rancagua, Chile."},
    {"year": "2001", "title": "Exposición colectiva, Corporación Cultural Municipal de Valdivia, Chile."},
]

other_workshops = [
    "Resultados Taller de Técnicas Textiles en San Vicente de Tagua Tagua",
    "Resultados del taller de Bordado en San Pedro de Atacama",
    "Residencia de Arte Colaborativo Alhue",
    "Residencia de Arte Colaborativo en Alicahue",
    "Residencia de Arte Colaborativo en Baquedano",
    "Residencia de Arte Colaborativo en Tocopilla",
    "Residencia de Arte Colaborativo en Antofagasta",
]

about_page = {
    "title": "Sobre Max",
    "description": "Biografía, trayectoria y enfoque artístico de Max Sepúlveda, artista visual, artesano y gestor cultural chileno. Más de 20 años de experiencia en arte colaborativo, cerámica y textiles.",
    "blocks": [
        {
            "type": "hero",
            "title": "Sobre Max",
            "subtitle": "Biografía, obra y gestión cultural desde San Vicente de Tagua Tagua hacia comunidades de Chile y Latinoamérica.",
            "cta": {"text": "Ver Proyectos", "url": "/es/proyectos/"},
            "background_image": "assets/images/header-8.jpg",
            "background_class": "sf-hero__background--header",
            "portrait_image": "assets/images/perfil.jpg",
            "portrait_alt": "Retrato de Max Sepúlveda",
            "variant": "about",
        },
        {
            "type": "text_section",
            "title": "Biografía",
            "content": "<p><strong>Maximiliano 'Max' Sepúlveda Zúñiga</strong> (n. 1974) es un artista visual, artesano y gestor cultural oriundo de San Vicente de Tagua Tagua, Chile. Su trabajo abarca <strong>alfarería, cerámica, textiles, arte colaborativo y dirección de arte audiovisual</strong>, disciplinas en las que ha desarrollado una amplia producción creativa por más de veinte años.</p><p>Se formó junto a maestros artesanos y artistas visuales de Latinoamérica, complementando su aprendizaje en Chile, Argentina y México. Esa formación multicultural atraviesa su obra y su manera de trabajar con comunidades, integrando técnicas tradicionales con una mirada contemporánea y territorial.</p>",
            "image": "assets/images/perfil.jpg",
            "image_position": "right",
            "image_alt": "Max Sepúlveda trabajando sobre un mural",
            "variant": "default",
        },
        {
            "type": "timeline",
            "title": "Trayectoria",
            "subtitle": "Hitos y proyectos clave en más de 20 años de carrera artística.",
            "milestones": milestones,
        },
        {
            "type": "quote",
            "quote": "Vincular a la comunidad desde la sensibilidad, generando lazos que van más allá de lo cotidiano. El arte comunitario y colaborativo es una herramienta de transformación social.",
            "author": "Max Sepúlveda",
            "source": "Filosofía de Arte Colaborativo",
            "variant": "highlight",
        },
        {
            "type": "text_section",
            "title": "Obra y enfoque",
            "content": "<p>La práctica de Max cruza <strong>cerámica, alfarería, bordado, telar, batik, pintura en seda y dirección de arte audiovisual</strong>. Su lenguaje mezcla oficios tradicionales, memoria local y experimentación material para construir relatos visuales con fuerte contenido social.</p><p>Muchas de sus obras nacen de procesos participativos: artista y comunidad reflexionan sobre el territorio, sus problemáticas e identidad, y desde ese diálogo co-crean piezas que visibilizan patrimonio, historias y vínculos afectivos.</p>",
            "variant": "default",
        },
        {
            "type": "text_section",
            "title": "Trayectoria y gestión cultural",
            "content": "<p>A lo largo de su trayectoria ha realizado talleres, seminarios, residencias y exposiciones en distintas regiones de Chile y en países como Uruguay, Costa Rica, México y Nueva Zelanda. Su trabajo ha llegado a espacios comunitarios, museos, escuelas de arte y programas públicos de formación.</p><p>Como gestor cultural, impulsa proyectos que empoderan a las comunidades y dejan capacidades instaladas: rescate patrimonial, formación en oficios, mediación artística y creación colaborativa. Ha trabajado con instituciones como el <strong>Museo Violeta Parra</strong>, la <strong>Fundación Superación de la Pobreza</strong> y programas como <strong>Red Cultura</strong>.</p>",
            "image": "assets/images/header.jpg",
            "image_position": "left",
            "image_alt": "Registro de trabajo comunitario liderado por Max Sepúlveda",
            "variant": "default",
        },
        {
            "type": "text_section",
            "title": "Trayectoria internacional",
            "content": "<p>La obra de Max ha trascendido su territorio de origen mediante exposiciones, residencias y colaboraciones en distintos países. Ha desarrollado proyectos y muestras en <strong>Uruguay, Costa Rica, México y Nueva Zelanda</strong>, además de compartir su trabajo en diversas regiones de Chile.</p><p>Ese recorrido internacional no aparece como una expansión desligada de lo local, sino como una forma de tender puentes entre culturas, oficios y memorias. En cada contexto, su práctica dialoga con comunidades, saberes artesanales y símbolos territoriales para construir procesos de intercambio y co-creación.</p>",
            "variant": "default",
        },
        {
            "type": "quote",
            "quote": "Su objetivo es visibilizar, valorar, proteger y revitalizar las identidades locales a través del arte.",
            "author": "Max Sepúlveda",
            "source": "Visión artística y territorial",
            "variant": "highlight",
        },
        {
            "type": "text_section",
            "title": "Hitos y reconocimientos",
            "content": "<p>Entre los hitos más significativos de su trayectoria se encuentran el proyecto <strong>Widüfe Kuyfiche - Alfarero Ancestral</strong>, financiado por Fondart; el desarrollo de <strong>Bordado Urbano</strong> en Calama; y el proyecto <strong>Bordado Charrúa de la Memoria</strong>, reconocido por los Fondos Concursables para la Cultura del Uruguay.</p><p>También destacan su residencia y exposición en la School of Art de Dunedin, Nueva Zelanda, su participación en Costa Rica Fashion Week y su trabajo sostenido de mediación artística y formación de oficios en espacios comunitarios e institucionales.</p>",
            "variant": "default",
        },
        {
            "type": "text_section",
            "title": "Exposiciones y publicaciones",
            "content": "<p>Su trabajo también ha circulado en documentales, entrevistas y publicaciones especializadas que profundizan en el cruce entre arte, oficio y comunidad.</p><ul><li><strong>Artefacto 02x04:</strong> episodio dedicado a su trayectoria como alfarero y artista textil.</li><li><strong>Documentales de proyecto:</strong> registros audiovisuales de <em>Bordado Urbano</em> y <em>Bordado Charrúa</em>, donde participó además como director de arte.</li><li><strong>Catálogos y libros:</strong> presencia en publicaciones sobre artesanía chilena contemporánea y en el libro <em>Arte Textil y Resistencia</em>.</li></ul>",
            "variant": "default",
        },
        {
            "type": "name_list",
            "title": "Empresas, instituciones y organizaciones",
            "subtitle": "Espacios públicos, privados, educativos y comunitarios con los que ha trabajado o colaborado.",
            "items": institutions,
        },
        {
            "type": "name_list",
            "title": "Colaboraciones",
            "subtitle": "Red de espacios culturales, museos, medios, instituciones educativas y comunidades vinculadas a su trayectoria.",
            "items": collaborations,
        },
        {
            "type": "dated_list",
            "title": "Premios y reconocimientos",
            "subtitle": "Reconocimientos institucionales y selecciones relevantes.",
            "items": awards,
        },
        {
            "type": "dated_list",
            "title": "Exposiciones",
            "subtitle": "Selección cronológica de exposiciones individuales y colectivas.",
            "items": exhibitions,
        },
        {
            "type": "portfolio_grid",
            "title": "Proyectos destacados",
            "subtitle": "Una selección de obras y procesos colaborativos representativos de su trayectoria.",
            "show_featured_only": True,
            "max_items": 7,
            "show_link_to_all": True,
            "variant": "default",
        },
        {
            "type": "contact",
            "title": "Contacto",
            "text": "Si quieres conocer más sobre su trabajo, proponer una colaboración o invitarlo a un proyecto, puedes escribirle directamente.",
            "email": "maxsepulvedaz@gmail.com",
            "phone": "+56 9 8654 5810",
            "phone_link": "+56986545810",
            "social_links": [
                {
                    "platform": "instagram",
                    "label": "Instagram de Max Sepúlveda",
                    "url": "https://www.instagram.com/maxartepopular/",
                },
                {
                    "platform": "facebook",
                    "label": "Facebook Max Sepúlveda Artepopular",
                    "url": "https://www.facebook.com/MaxArteVisual/",
                },
                {
                    "platform": "youtube",
                    "label": "YouTube Warisdey1974",
                    "url": "https://www.youtube.com/@Warisdey1974",
                },
            ],
            "variant": "default",
        },
    ],
}

home_blocks = [
    {
        "type": "hero",
        "title": "Max Sepúlveda",
        "subtitle": "Artista visual, artesano y gestor cultural.",
        "background_image": "assets/images/max-sepulveda-hero.jpg",
        "background_class": "sf-hero__background--header",
        "variant": "minimal",
    },
    {
        "type": "discipline_showcase",
        "title": "Áreas de obra y oficio",
        "subtitle": "Oficios, técnicas y procesos colaborativos que articulan su trabajo.",
    },
    {
        "type": "text_section",
        "title": "Sobre Max",
        "content": "<p>Artista visual, artesano y gestor cultural oriundo de San Vicente de Tagua Tagua, Chile. Más de veinte años construyendo obra donde conviven la alfarería, el textil, el arte colaborativo y la dirección audiovisual.</p><p>Su trabajo nace del diálogo con comunidades: juntos reflexionan sobre el territorio, la memoria y la identidad, y desde ese encuentro co-crean obras que visibilizan patrimonio y vínculos afectivos.</p><p><a href=\"sobre-max/\">Conocer su trayectoria completa →</a></p>",
        "image": "assets/images/perfil.jpg",
        "image_position": "right",
        "image_alt": "Max Sepúlveda trabajando sobre un mural",
        "variant": "default",
    },
    {
        "type": "contact",
        "title": "Contacto",
        "text": "¿Interesado en colaborar, contratar un taller o conocer más sobre su obra? No dudes en escribirle.",
        "email": "maxsepulvedaz@gmail.com",
        "phone": "+56 9 8654 5810",
        "phone_link": "+56986545810",
        "social_links": [
            {"platform": "instagram", "url": "https://www.instagram.com/maxartepopular/", "label": "Instagram"},
            {"platform": "facebook", "url": "https://www.facebook.com/MaxArteVisual/", "label": "Facebook"},
            {"platform": "youtube", "url": "https://www.youtube.com/@Warisdey1974", "label": "YouTube"},
        ],
        "variant": "default",
    },
]
