site = {
    "name": "Max Sepúlveda",
    "title_suffix": "Portfolio",
    "description": "Portfolio de Max Sepúlveda, artista visual, artesano y gestor cultural chileno.",
    "tagline": "Artista visual · Artesano · Gestor cultural",
    "email": "maxsepulvedaz@gmail.com",
    "year": "2026",
}

projects = [
    {
        "title": "Bordado Urbano",
        "slug": "bordado-urbano",
        "date": "2012-05-15",
        "summary": "Proyecto de arte comunitario en Calama (2012). Los habitantes bordaron colectivamente un mapa de 3x2 metros representando sus sueños e historias.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-urbano/",
        "tags": ["Arte Comunitario", "Textil", "Calama", "Documental"],
        "content": [
            {
                "type": "text_section",
                "title": "Un tapiz de sueños colectivos",
                "content": "<p>Proyecto de arte comunitario en el que los habitantes de Calama bordaron colectivamente un mapa de <strong>3 x 2 metros</strong> representando sus sueños e historias para la ciudad.</p><p>Fue una intervención pública realizada en distintas locaciones (ferias, paseos peatonales, mercados), acompañada por la filmación de un <strong>documental</strong> sobre la experiencia.</p><p>El resultado fue un tapiz urbano único, fruto del trabajo conjunto del artista con más de un centenar de participantes locales.</p>",
                "variant": "default",
            },
            {
                "type": "quote",
                "quote": "El bordado es una herramienta convocante que invita a la participación de personas de todas las edades.",
                "author": "Max Sepúlveda",
                "variant": "highlight",
            },
        ],
    },
    {
        "title": "Bordado Charrúa de la Memoria",
        "slug": "bordado-charrua-de-la-memoria",
        "date": "2016-11-20",
        "summary": "Mapa textil colectivo de la costa de Rocha, Uruguay. Ganador de los Fondos Concursables para la Cultura del MEC uruguayo (2016).",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-charrua-de-la-memoria/",
        "tags": ["Arte Comunitario", "Textil", "Uruguay", "Premios"],
        "content": [
            {
                "type": "text_section",
                "title": "Rescatando la memoria costera",
                "content": "<p>Proyecto ganador de los <strong>Fondos Concursables para la Cultura</strong> del Ministerio de Educación y Cultura de Uruguay.</p><p>Consistió en la creación de un mapa textil colectivo de la costa de Rocha, bordado in situ por habitantes y visitantes en <strong>cinco localidades costeras</strong>.</p><p>Durante el proceso, la gente compartió anécdotas sobre los lugares que dejaron huella en sus vidas: historias de amor, aventuras, desventuras —y también lo que se perdió, lo que cambiaría y lo que falta en su entorno. Sepúlveda actuó como facilitador: enseñó técnicas de bordado en el momento, de modo que incluso quienes nunca habían bordado pudieron contribuir con sus puntadas.</p><p>El proyecto culminó con la exhibición del mapa bordado y la proyección del documental en las mismas comunidades donde se gestó, así como en Montevideo y circuitos internacionales.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Textiles y Alfarería del Tagua Tagua",
        "slug": "textiles-y-alfareria-del-tagua-tagua",
        "date": "2018-08-10",
        "summary": "Exposición individual en la School of Art de Dunedin, Nueva Zelanda (2018). Diálogo entre la identidad cultural de Tagua Tagua y la tradición maorí.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/residencia-artistica-en-nueva-zelanda/",
        "tags": ["Exposición", "Internacional", "Nueva Zelanda", "Cerámica", "Textil"],
        "content": [
            {
                "type": "text_section",
                "title": "Intercambio Cultural Chile-Nueva Zelanda",
                "content": "<p>Exposición individual realizada en la <strong>School of Art de Dunedin</strong>, como resultado de una residencia artística en Nueva Zelanda.</p><p>La muestra presentó una selección de obras en cerámica y textil inspiradas en la identidad cultural de <strong>Tagua Tagua</strong> y su diálogo con la tradición maorí.</p><p>Como parte de la residencia, Sepúlveda ofreció un <strong>taller de alfarería ancestral</strong> en el estudio de cerámica de la escuela, compartiendo técnicas tradicionales chilenas con estudiantes neozelandeses. El intercambio enriqueció su práctica, incorporando influencias del arte oceánico.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Widüfe Kuyfiche – Alfarero Ancestral",
        "slug": "widufe-kuyfiche-alfarero-ancestral",
        "date": "2006-03-01",
        "summary": "Investigación y rescate de la alfarería indígena de la zona central de Chile. Proyecto FONDART 2006.",
        "featured": True,
        "tags": ["Investigación", "Cerámica", "Fondart", "Patrimonio"],
        "content": [
            {
                "type": "text_section",
                "title": "Hacedores de Greda",
                "content": "<p>Proyecto financiado por el <strong>Fondo Nacional de Desarrollo Cultural y las Artes (FONDART)</strong>.</p><p>Consistió en una investigación y rescate de la alfarería indígena de la zona central de Chile, que culminó en una exposición exhibida en la <strong>Sala Samuel Román</strong> de la Casa de la Cultura de Rancagua. La muestra presentó piezas de cerámica inspiradas en técnicas prehispánicas, poniendo en valor el oficio del alfarero tradicional.</p><p><em>Widüfe</em> en mapudungun significa 'alfarero' o 'hacedor de greda'. Fue un hito temprano en la carrera de Sepúlveda, consolidando su vínculo con el patrimonio de la zona central de Chile.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Murales Textiles Colaborativos",
        "slug": "murales-textiles-colaborativos",
        "date": "2020-01-15",
        "summary": "Serie de intervenciones colaborativas en que comunidades crean murales de telas y bordados para espacios públicos. Incluye el mural 'Inti Ray' en Calama, financiado por Codelco.",
        "featured": True,
        "tags": ["Arte Comunitario", "Textil", "Muralismo", "Codelco"],
        "content": [
            {
                "type": "text_section",
                "title": "Mosaicos Comunitarios",
                "content": "<p>Diversas intervenciones lideradas por Sepúlveda donde comunidades completas crean <strong>murales hechos de telas y bordados</strong> que se instalan en espacios públicos locales a modo de mosaico comunitario.</p><p>Un ejemplo destacado es el mural <strong>'Inti Ray'</strong> en Calama, resultado del proyecto <em>Rescate del Patrimonio e Identidad Cultural Textil de los Pobladores de la Inti Ray</em>, financiado por <strong>Codelco</strong> dentro del programa Calama Participa. La obra fue conformada por múltiples paños bordados o tejidos por diferentes manos, representando símbolos y relatos de la comunidad.</p><p>Estas obras colectivas se han realizado en poblados rurales y barrios urbanos de distintas regiones, fortaleciendo el sentido de identidad y pertenencia de sus autores colectivos.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Residencia Artística Alicahue",
        "slug": "residencia-artistica-alicahue",
        "date": "2016-10-01",
        "summary": "Residencia del programa Red Cultura en la Región de Valparaíso (2016), trabajando con comunidades locales.",
        "featured": False,
        "tags": ["Arte Comunitario", "Residencia", "Valparaíso", "Red Cultura"],
        "content": [
            {
                "type": "text_section",
                "title": "Arte colaborativo en el Valle de Alicahue",
                "content": "<p>Seleccionado por el programa <strong>Red Cultura</strong> del Ministerio de las Culturas para una residencia de arte colaborativo en el <strong>Valle de Alicahue</strong>, Región de Valparaíso.</p><p>Durante la residencia, Sepúlveda trabajó junto a comunidades locales en intervenciones artísticas que partieron de la reflexión sobre el territorio, la memoria y la identidad del valle. El proceso buscó dejar capacidades instaladas y visibilizar el patrimonio cultural de la zona a través de la co-creación.</p>",
                "variant": "default",
            },
        ],
    },
]

about_page = {
    "title": "Sobre Max",
    "description": "Biografía, trayectoria y enfoque artístico de Max Sepúlveda, artista visual, artesano y gestor cultural chileno.",
    "blocks": [
        {
            "type": "hero",
            "title": "Sobre Max",
            "subtitle": "Biografía, obra y gestión cultural desde San Vicente de Tagua Tagua hacia comunidades de Chile y Latinoamérica.",
            "cta": {"text": "Ver Proyectos", "url": "/es/proyectos/"},
            "background_image": "assets/images/header.jpg",
            "background_class": "sf-hero__background--header",
            "portrait_image": "assets/images/perfil.jpg",
            "portrait_alt": "Retrato de Max Sepúlveda",
            "variant": "default",
        },
        {
            "type": "text_section",
            "title": "Biografía",
            "content": "<p><strong>Maximiliano 'Max' Sepúlveda Zúñiga</strong> (n. 1974) es un artista visual, artesano y gestor cultural oriundo de San Vicente de Tagua Tagua, Chile. Su trabajo abarca <strong>alfarería, cerámica, textiles, arte colaborativo y dirección de arte audiovisual</strong>, disciplinas en las que ha desarrollado una amplia producción creativa por más de veinte años.</p><p>Se formó junto a maestros artesanos y artistas visuales de Latinoamérica, complementando su aprendizaje en Chile, Argentina y México. Esa formación multicultural atraviesa su obra y su manera de trabajar con comunidades, integrando técnicas tradicionales con una mirada contemporánea y territorial.</p>",
            "image": "assets/images/perfil.jpg",
            "image_position": "right",
            "image_alt": "Max Sepúlveda trabajando sobre un mural",
            "variant": "default",
        },
        {
            "type": "quote",
            "quote": "Vincular a la comunidad desde la sensibilidad, generando lazos que van más allá de lo cotidiano. El arte comunitario y colaborativo es una herramienta de transformación social.",
            "author": "Max Sepúlveda",
            "source": "Filosofía de Arte Colaborativo",
            "variant": "highlight",
        },
        {
            "type": "text_section",
            "title": "Obra y enfoque",
            "content": "<p>La práctica de Max cruza <strong>cerámica, alfarería, bordado, telar, batik, pintura en seda y dirección de arte audiovisual</strong>. Su lenguaje mezcla oficios tradicionales, memoria local y experimentación material para construir relatos visuales con fuerte contenido social.</p><p>Muchas de sus obras nacen de procesos participativos: artista y comunidad reflexionan sobre el territorio, sus problemáticas e identidad, y desde ese diálogo co-crean piezas que visibilizan patrimonio, historias y vínculos afectivos.</p>",
            "variant": "default",
        },
        {
            "type": "text_section",
            "title": "Trayectoria y gestión cultural",
            "content": "<p>A lo largo de su trayectoria ha realizado talleres, seminarios, residencias y exposiciones en distintas regiones de Chile y en países como Uruguay, Costa Rica, México y Nueva Zelanda. Su trabajo ha llegado a espacios comunitarios, museos, escuelas de arte y programas públicos de formación.</p><p>Como gestor cultural, impulsa proyectos que empoderan a las comunidades y dejan capacidades instaladas: rescate patrimonial, formación en oficios, mediación artística y creación colaborativa. Ha trabajado con instituciones como el <strong>Museo Violeta Parra</strong>, la <strong>Fundación Superación de la Pobreza</strong> y programas como <strong>Red Cultura</strong>.</p>",
            "image": "assets/images/header.jpg",
            "image_position": "left",
            "image_alt": "Registro de trabajo comunitario liderado por Max Sepúlveda",
            "variant": "default",
        },
        {
            "type": "text_section",
            "title": "Trayectoria internacional",
            "content": "<p>La obra de Max ha trascendido su territorio de origen mediante exposiciones, residencias y colaboraciones en distintos países. Ha desarrollado proyectos y muestras en <strong>Uruguay, Costa Rica, México y Nueva Zelanda</strong>, además de compartir su trabajo en diversas regiones de Chile.</p><p>Ese recorrido internacional no aparece como una expansión desligada de lo local, sino como una forma de tender puentes entre culturas, oficios y memorias. En cada contexto, su práctica dialoga con comunidades, saberes artesanales y símbolos territoriales para construir procesos de intercambio y co-creación.</p>",
            "variant": "default",
        },
        {
            "type": "quote",
            "quote": "Su objetivo es visibilizar, valorar, proteger y revitalizar las identidades locales a través del arte.",
            "author": "Max Sepúlveda",
            "source": "Visión artística y territorial",
            "variant": "highlight",
        },
        {
            "type": "text_section",
            "title": "Hitos y reconocimientos",
            "content": "<p>Entre los hitos más significativos de su trayectoria se encuentran el proyecto <strong>Wid\u00fcfe Kuyfiche - Alfarero Ancestral</strong>, financiado por Fondart; el desarrollo de <strong>Bordado Urbano</strong> en Calama; y el proyecto <strong>Bordado Charr\u00faa de la Memoria</strong>, reconocido por los Fondos Concursables para la Cultura del Uruguay.</p><p>Tambi\u00e9n destacan su residencia y exposici\u00f3n en la School of Art de Dunedin, Nueva Zelanda, su participaci\u00f3n en Costa Rica Fashion Week y su trabajo sostenido de mediaci\u00f3n art\u00edstica y formaci\u00f3n de oficios en espacios comunitarios e institucionales.</p>",
            "variant": "default",
        },
        {
            "type": "text_section",
            "title": "Exposiciones y publicaciones",
            "content": "<p>Su trabajo también ha circulado en documentales, entrevistas y publicaciones especializadas que profundizan en el cruce entre arte, oficio y comunidad.</p><ul><li><strong>Artefacto 02x04:</strong> episodio dedicado a su trayectoria como alfarero y artista textil.</li><li><strong>Documentales de proyecto:</strong> registros audiovisuales de <em>Bordado Urbano</em> y <em>Bordado Charrúa</em>, donde participó además como director de arte.</li><li><strong>Catálogos y libros:</strong> presencia en publicaciones sobre artesanía chilena contemporánea y en el libro <em>Arte Textil y Resistencia</em>.</li></ul>",
            "variant": "default",
        },
        {
            "type": "portfolio_grid",
            "title": "Proyectos destacados",
            "subtitle": "Una selección de obras y procesos colaborativos representativos de su trayectoria.",
            "show_featured_only": True,
            "max_items": 6,
            "show_link_to_all": True,
            "variant": "default",
        },
        {
            "type": "contact",
            "title": "Contacto",
            "text": "Si quieres conocer más sobre su trabajo, proponer una colaboración o invitarlo a un proyecto, puedes escribirle directamente.",
            "email": "maxsepulvedaz@gmail.com",
            "social_links": [
                {
                    "platform": "instagram",
                    "label": "Instagram de Max Sepúlveda",
                    "url": "https://www.instagram.com/maxartevisual/",
                }
            ],
            "variant": "default",
        },
    ],
}

home_blocks = [
    {
        "type": "hero",
        "title": "Max Sepúlveda",
        "subtitle": "Arte colaborativo, cerámica y textiles. Obra construida con comunidades de Chile y el mundo.",
        "cta": {"text": "Ver Proyectos", "url": "/es/proyectos/"},
        "background_image": "assets/images/header.jpg",
        "background_class": "sf-hero__background--header",
        "portrait_image": "assets/images/perfil.jpg",
        "portrait_alt": "Retrato de Max Sepúlveda",
        "variant": "default",
    },
    {
        "type": "portfolio_grid",
        "title": "Proyectos",
        "subtitle": "Una selección de obras y procesos colaborativos representativos de su trayectoria.",
        "show_featured_only": True,
        "max_items": 6,
        "show_link_to_all": True,
        "variant": "default",
    },
    {
        "type": "text_section",
        "title": "Sobre Max",
        "content": "<p>Artista visual, artesano y gestor cultural oriundo de San Vicente de Tagua Tagua, Chile. Más de veinte años construyendo obra donde conviven la alfarería, el textil, el arte colaborativo y la dirección audiovisual.</p><p>Su trabajo nace del diálogo con comunidades: juntos reflexionan sobre el territorio, la memoria y la identidad, y desde ese encuentro co-crean obras que visibilizan patrimonio y vínculos afectivos.</p><p><a href=\"sobre-max/\">Conocer su trayectoria completa →</a></p>",
        "image": "assets/images/perfil.jpg",
        "image_position": "right",
        "image_alt": "Max Sepúlveda trabajando sobre un mural",
        "variant": "default",
    },
    {
        "type": "contact",
        "title": "Contacto",
        "text": "¿Interesado en colaborar, contratar un taller o adquirir obras? No dudes en escribirle.",
        "email": "maxsepulvedaz@gmail.com",
        "social_links": [
            {"platform": "instagram", "url": "https://instagram.com/maxartevisual", "label": "Instagram"},
            {"platform": "website", "url": "https://maxsepulvedaartevisual.com", "label": "Sitio web"},
        ],
        "variant": "default",
    },
]