"""
Data source for the English version of Max Sepúlveda's portfolio.
"""

from __future__ import annotations

site = {
    "name": "Max Sepúlveda",
    "title_suffix": "Portfolio",
    "description": "Professional portfolio of Max Sepúlveda, Chilean visual artist, artisan, and cultural manager. Over 20 years of experience in collaborative art, ceramics, and textiles.",
    "tagline": "Visual Artist · Artisan · Cultural Manager",
    "email": "maxsepulvedaz@gmail.com",
    "phone": "+56 9 8654 5810",
    "phone_link": "+56986545810",
    "location": "San Vicente de Tagua Tagua, Chile",
    "year": "2026",
    "website": "https://maxsepulvedaartevisual.com",
    "instagram": "https://www.instagram.com/maxartepopular/",
    "facebook": "https://www.facebook.com/MaxArteVisual/",
    "youtube": "https://www.youtube.com/@Warisdey1974",
}


def gallery(folder: str, names: list[str]) -> list[str]:
    return [f"assets/images/gallery/{folder}/{name}" for name in names]


disciplines = [
    {
        "name": "Pottery",
        "description": "Creation of utilitarian and decorative pieces using ancestral techniques and designs.",
        "icon": "pottery",
        "image": "assets/images/disciplinas/alfareria.jpeg",
        "anchor": "alfareria",
        "panel": "fullbleed",
    },
    {
        "name": "Ceramics",
        "description": "Mold casting, modeling, sgraffito, engobes, and glazes. Exploration of traditional forms with a contemporary vision.",
        "icon": "ceramic",
        "image": "assets/images/disciplinas/ceramica.jpeg",
        "anchor": "ceramica",
        "panel": "fullbleed",
    },
    {
        "name": "Embroidery",
        "description": "Exploration of 15 traditional stitches.",
        "icon": "embroidery",
        "image": "assets/images/disciplinas/bordado.jpeg",
        "anchor": "bordado",
        "panel": "fullbleed",
    },
    {
        "name": "Batik & Embroidery",
        "description": "Contemporary fusion of batik and embroidery celebrating natural and cultural heritage.",
        "icon": "batik",
        "image": "assets/images/disciplinas/batik-y-bordado.jpeg",
        "anchor": "batik-y-bordado",
        "panel": "fullbleed",
    },
    {
        "name": "Weaving & Textiles",
        "description": "Mapuche loom, rigid heddle loom, frame loom, artistic tapestry, Andean cordmaking, and textile jewelry.",
        "icon": "weaving",
        "image": "assets/images/disciplinas/tejidos.jpeg",
        "anchor": "tejidos",
        "panel": "fullbleed",
    },
    {
        "name": "Lanigraphy (Yarn Painting)",
        "description": "Technique of adhering wool yarns and cords onto wood or cardboard surfaces.",
        "icon": "weaving",
        "image": "assets/images/disciplinas/lanigrafia.jpeg",
        "anchor": "lanigrafia",
        "panel": "fullbleed",
    },
    {
        "name": "Resist Dyeing Techniques",
        "description": "Batik, silk painting, and tie-dye (shibori). Pre-Columbian and contemporary designs.",
        "icon": "batik",
        "image": "assets/images/disciplinas/tecnicas-de-tenido-por-reserva.jpeg",
        "anchor": "tecnicas-de-tenido-por-reserva",
        "panel": "fullbleed",
    },
    {
        "name": "Audiovisual Production",
        "description": "Art direction for short films and documentaries documenting community creative processes.",
        "icon": "video",
        "image": "assets/images/disciplinas/audiovisuales.jpg",
        "anchor": "audiovisuales",
        "panel": "fullbleed",
    },
    {
        "name": "Collaborative Art",
        "description": "Memory map embroideries, mixed embroidery and batik murals, painted murals, street parades, and artistic interventions in the natural and cultural landscape. Collaborative art as a vehicle for community participation and social transformation.",
        "icon": "embroidery",
        "image": "assets/images/disciplinas/arte-colaborativo.jpeg",
        "anchor": "arte-colaborativo",
        "panel": "fullbleed",
    },
]

projects = [
    {
        "title": "Urban Embroidery",
        "slug": "bordado-urbano",
        "date": "2012-05-15",
        "summary": "Collaborative project in Calama (2012): residents collectively embroidered a 3x2-meter map expressing their dreams, stories, and aspirations, accompanied by a documentary featuring local musicians, songwriters, and dancers.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-urbano/",
        "tags": ["Community Art", "Textile", "Calama", "Documentary"],
        "image": "assets/images/gallery/bordado-urbano/bordado-urbano-05.jpg",
        "gallery": gallery(
            "bordado-urbano",
            [
                "bordado-urbano-01.jpg",
                "bordado-urbano-02.jpg",
                "bordado-urbano-03.jpg",
                "bordado-urbano-04.jpg",
                "bordado-urbano-05.jpg",
                "bordado-urbano-06.jpg",
                "bordado-urbano-07.jpg",
                "bordado-urbano-08.jpg",
                "bordado-urbano-09.jpg",
                "bordado-urbano-10.jpg",
                "bordado-urbano-11.jpg",
                "bordado-urbano-12.jpg",
                "bordado-urbano-13.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "A Tapestry of Collective Dreams",
                "content": "<p><em>Urban Embroidery</em> was a collaborative project conducted by artist Max Sepúlveda in the city of <strong>Calama, Chile</strong>, in <strong>2012</strong>. Public interventions were held where participants embroidered a <strong>3 x 2 meter</strong> map, capturing through colorful stitches their dreams, stories of love and heartbreak, aspirations, needs, abundances, conflicts, and the vision for their city's future.</p><p>Simultaneously, a <strong>documentary</strong> of the experience was produced, featuring music bands, singer-songwriters, and dancers from Calama.</p><p>The collaborative artwork, embroidered by interviewed residents, participants, and textile artist Max Sepúlveda, took place across diverse locations in Calama, such as <strong>street markets, Paseo Ramírez, Mercado Modelo, La Cascada, schools, and city squares</strong>—settings that triggered this search for identity immortalized through audiovisual storytelling.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Charrúa Memory Embroidery",
        "slug": "bordado-charrua-de-la-memoria",
        "date": "2016-11-20",
        "summary": "Collaborative project by Max Sepúlveda and the Cine del Cono Sur collective across five coastal towns in Rocha, Uruguay (2016), funded by the Competitive Culture Fund of Uruguay's Ministry of Education and Culture.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-charrua-de-la-memoria/",
        "tags": ["Community Art", "Textile", "Uruguay", "Awards"],
        "image": "assets/images/gallery/bordado-charrua/bordado-charrua-05.jpg",
        "gallery": gallery(
            "bordado-charrua",
            [
                "bordado-charrua-01.jpg",
                "bordado-charrua-02.jpg",
                "bordado-charrua-03.jpg",
                "bordado-charrua-04.jpg",
                "bordado-charrua-05.jpg",
                "bordado-charrua-06.jpg",
                "bordado-charrua-07.jpg",
                "bordado-charrua-08.jpg",
                "bordado-charrua-09.jpg",
                "bordado-charrua-10.jpg",
                "bordado-charrua-11.jpg",
                "bordado-charrua-12.jpg",
                "bordado-charrua-13.jpg",
                "bordado-charrua-14.jpg",
                "bordado-charrua-15.jpg",
                "bordado-charrua-16.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Rescuing Coastal Memory",
                "content": "<p>The <em>Charrúa Memory Embroidery</em> was a collaborative project carried out by artist Max Sepúlveda and the <strong>Cine del Cono Sur</strong> collective in <strong>five coastal towns of Rocha Department, Uruguay</strong>, in <strong>2016</strong>, supported by the <strong>Competitive Culture Fund of Uruguay's Ministry of Education and Culture (MEC)</strong>.</p><p>Public interventions were held where participants embroidered a <strong>3 x 2 meter</strong> map representing their coastal resort, their town, and their community through colorful embroidery stitches. During this process, residents shared stories of places that left a mark on their lives, tales of love, adventures, and misadventures, magical and identity-defining sites, what has been lost, what they would change, what their community needs, and the areas that should be preserved and protected.</p><p>Singer-songwriters, musicians, and dancers joined the participants, enriching the narrative captured in a comprehensive <strong>documentary</strong>.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Artist Residency in New Zealand",
        "slug": "textiles-y-alfareria-del-tagua-tagua",
        "date": "2018-08-10",
        "summary": "Artistic residency at the Dunedin School of Art at Otago Polytechnic, New Zealand (2018), featuring a solo exhibition, ancestral Tagua Tagua pottery workshop, cultural mediation sessions, and publication in Scope Journal.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/residencia-artistica-en-nueva-zelanda/",
        "tags": ["Exhibition", "International", "New Zealand", "Ceramics", "Textiles"],
        "image": "assets/images/gallery/nueva-zelanda/nueva-zelanda-13.jpg",
        "gallery": gallery(
            "nueva-zelanda",
            [
                "nueva-zelanda-01.jpg",
                "nueva-zelanda-02.jpg",
                "nueva-zelanda-03.jpg",
                "nueva-zelanda-04.jpg",
                "nueva-zelanda-05.jpg",
                "nueva-zelanda-06.jpg",
                "nueva-zelanda-07.jpg",
                "nueva-zelanda-08.jpg",
                "nueva-zelanda-09.jpg",
                "nueva-zelanda-10.jpg",
                "nueva-zelanda-11.jpg",
                "nueva-zelanda-12.jpg",
                "nueva-zelanda-13.jpg",
                "nueva-zelanda-14.jpg",
                "nueva-zelanda-15.jpg",
                "nueva-zelanda-16.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Chile–New Zealand Cultural Exchange",
                "content": "<p>In <strong>2018</strong>, the artist completed an <strong>artistic residency at the Dunedin School of Art at Otago Polytechnic, New Zealand</strong>, which included the solo exhibition titled <em>Textiles and Pottery of Tagua Tagua</em>.</p><p>In the school's ceramic studio, he conducted an <strong>ancestral pottery workshop using the Tagua Tagua technique</strong> for students, faculty, and local artists. He also led <strong>cultural mediation</strong> sessions in both the gallery and the main campus Hub.</p><p>Additionally, he published a research article in <strong>Scope Contemporary Research Topics: Art and Design</strong> detailing his experience during the residency.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Exhibition: Widufe Kuyfiche – Ancestral Potter",
        "slug": "widufe-kuyfiche-alfarero-ancestral",
        "date": "2016-03-01",
        "summary": "Creation of 22 pottery pieces highlighting the ancestral Tagua Tagua method. Project funded by the Chilean Ministry of Culture (2016), touring across the O'Higgins Region and New Zealand.",
        "featured": True,
        "tags": ["Research", "Ceramics", "Ancestral Pottery", "Heritage"],
        "image": "assets/images/proyectos/alfareria/DSC05935.JPG",
        "gallery": gallery(
            "alfareria",
            [f"alfareria-{i:02d}.jpg" for i in range(1, 34)],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Makers of Clay",
                "content": "<p>In <strong>2016</strong>, supported by a grant from the <strong>Chilean Ministry of Cultures, Arts and Heritage</strong>, the artist created and produced <strong>22 pottery pieces</strong> revitalizing the ancestral Tagua Tagua method: ornamental and utilitarian works inspired by regional pre-Columbian ceramics.</p><p>The pieces reflect cultural influences from the <strong>Inca, Mapuche, Diaguita, and Atacameño</strong> peoples, the ancient <strong>Bato and Llolleo</strong> cultures (300 BCE – 800 CE), and the subsequent <strong>Aconcagua</strong> culture (900 CE).</p><p>The traveling exhibition toured <strong>10 cultural centers across the O'Higgins Region</strong> over two years and was subsequently presented in <strong>New Zealand</strong>.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Collaborative Textile Murals",
        "slug": "murales-textiles-colaborativos",
        "date": "2020-01-15",
        "summary": "Photographic documentation of collaborative textile murals created by Max Sepúlveda together with local communities.",
        "featured": True,
        "tags": ["Community Art", "Textile", "Muralism", "Codelco"],
        "image": "assets/images/proyectos/intervenciones/20240703_201741.jpg",
        "gallery": gallery(
            "murales",
            [
                "mural-01.jpg",
                "mural-02.jpg",
                "mural-03.jpg",
                "mural-04.jpg",
                "mural-05.jpg",
                "mural-06.jpg",
                "mural-07.jpg",
                "mural-08.jpg",
            ],
        ),
        "content": [],
    },
    {
        "title": "Costa Rica Fashion Week 2019",
        "slug": "costa-rica-fashion-week-2019",
        "date": "2019-08-01",
        "summary": "Invitation to exhibit his work and pieces by the Tagua Tagua Textile Cooperative at Costa Rica Fashion Week 2019, including a lecture, batik workshop, and national media interviews.",
        "featured": True,
        "tags": ["Textile", "Fashion", "International", "Costa Rica"],
        "image": "assets/images/proyectos/general/stand CRFW.jpg",
        "gallery": gallery(
            "costa-rica-fashion-week",
            [
                "costa-rica-fashion-week-01.jpg",
                "costa-rica-fashion-week-02.jpg",
                "costa-rica-fashion-week-03.jpg",
                "costa-rica-fashion-week-04.jpg",
                "costa-rica-fashion-week-05.jpg",
                "costa-rica-fashion-week-06.jpg",
                "costa-rica-fashion-week-07.jpg",
                "costa-rica-fashion-week-08.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Textiles, Craft, and Contemporary Design",
                "content": "<p>The artist was invited to <strong>Costa Rica Fashion Week 2019</strong> to showcase his artworks alongside creations by the <strong>Tagua Tagua Textile Cooperative</strong>.</p><p>During his participation, he gave a lecture titled <em>Social Intervention through Textile Art</em>, taught a <strong>batik workshop</strong>, and was interviewed across national broadcast media.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Textile Techniques Workshop Results in San Vicente",
        "slug": "resultados-taller-tecnicas-textiles-san-vicente",
        "date": "2024-06-15",
        "summary": "Photographic documentation of the textile techniques workshop led by Max Sepúlveda in San Vicente de Tagua Tagua.",
        "featured": False,
        "tags": ["Workshop", "Textile", "Training"],
        "image": "assets/images/gallery/taller-san-vicente/taller-san-vicente-01.jpg",
        "gallery": gallery(
            "taller-san-vicente",
            [f"taller-san-vicente-{i:02d}.jpg" for i in range(1, 41)],
        ),
        "content": [],
    },
    {
        "title": "Embroidery & Batik Workshop Results in San Pedro de Atacama",
        "slug": "resultados-taller-bordado-batik-san-pedro-de-atacama",
        "date": "2023-06-15",
        "summary": "Photographic documentation of the embroidery and batik workshop led by Max Sepúlveda in San Pedro de Atacama.",
        "featured": False,
        "tags": ["Workshop", "Embroidery", "Batik"],
        "image": "assets/images/gallery/taller-bordado-batik-san-pedro/taller-bordado-batik-san-pedro-01.jpg",
        "gallery": gallery(
            "taller-bordado-batik-san-pedro",
            [f"taller-bordado-batik-san-pedro-{i:02d}.jpg" for i in range(1, 16)],
        ),
        "content": [],
    },
]

institutions = [
    "SQM",
    "Novandino Litio",
    "Corporación Proloa",
    "Ministry of Cultures, Arts and Heritage of Chile",
    "Ministry of Education and Culture of Uruguay",
    "Colegio Cryptocaria Alba de Peumo",
    "Regional Government of Antofagasta",
    "San Pedro de Atacama Culture Foundation",
    "Violeta Parra Museum",
    "Regional Government of O'Higgins",
    "Municipality of Santa Cruz",
    "Municipality of San Vicente de Tagua Tagua",
    "Ministry of Housing and Urban Development of Chile",
    "Rewe Waldorf School of San Vicente de Tagua Tagua",
    "Alcaman School of Doñihue",
    "Joyarte Jewelry School of Valdivia",
    "Agricultural Development Institute of Chile (INDAP)",
    "PRODEMU Foundation for Women's Development",
    "Calama Culture and Tourism Corporation",
    "Codelco Chile",
    "Daniel Omar Favero Cultural Center and Mamaroja Sustainable Development Center (Argentina)",
    'Rapa Nui Cultural Group "Maohi o Rapa Nui"',
    "National Women's Service of Chile",
    "Municipality of Rancagua",
    "Social Solidarity and Investment Fund (FOSIS Chile)",
    "Casa Taller Recreo-Arte Textil in Viña del Mar, Chile",
    "Factoría Violeta Textile School",
    "Municipality of Oberá, Argentina",
]

collaborations = [
    "Leritchitacks Cultural Space in San Pedro de Atacama",
    "Tinguiririca River Surveillance Board",
    "Humanos Publishing",
    "Regional Museum of Rancagua",
    "Ecositex",
    "Montecarmelo Cultural Center",
    "Pichilemu TV",
    "Gabriela Mistral Education Museum",
    "Costa Rica Fashion Week",
    "Otago Polytechnic (New Zealand)",
    "Villa Grimaldi Peace Park Corporation",
    "Linares Museum of Art and Craft (Chile)",
    "TVO San Vicente",
    "La Moneda Cultural Center (Chile)",
    "San Vicente Institute",
    "National Autonomous University of Mexico (UNAM)",
    "Chilean-Guatemalan Institute of Culture",
    "Cultural Corporation of the Municipality of Viña del Mar, Chile",
    "Ministry of Culture of the Government of Mexico",
    "National Unified Corporation of Higher Education of Colombia (CUN)",
    "Ministry of Culture of Costa Rica",
    "Pro O'Higgins Corporation",
    "Añañuca Corporation",
    "Tagua Tagua Lagoon School Museum",
    "Gabriela Mistral Cultural Center (GAM), Santiago",
    "Ayllu Sin Frontera Cultural Group in San Pedro de Atacama",
    "Xico Urban Weavers of Mexico City",
    "Gárgola Cultural Space in Santiago",
    "Pichidegua Cultural Estate",
    "Nelly Lemus Cultural Center in Antofagasta",
    "Municipal Cultural Corporation of Valdivia",
    "Family Health Center of San Vicente de Tagua Tagua",
    "Lircunlauta Museum",
    "Chépica Public Library",
    "Municipal Theater of Rengo",
    "Agustín Ross Cultural Center in Pichilemu",
    "Lolol Cultural Center",
    "Machalí Cultural Center",
    "Codegua Cultural Center",
    "Casa de la Cultura of Rancagua",
    "Lollapalooza 2022",
    "Municipality of Recoleta",
    "Provincial Government of Cachapoal",
    "Ojo del Desierto Cultural Center in Calama",
    "Archaeological Research Institute and Museum (Universidad Católica del Norte)",
    "Scope Contemporary Research Topics: Art & Design Journal (New Zealand)",
]

awards = [
    {"year": "2021", "title": "National selection for the Crafts in Pandemic Catalog, Ministry of Cultures, Arts and Heritage of Chile."},
    {"year": "2015", "title": "Artisan Recognition Award 2015, Municipality of San Vicente de Tagua Tagua, Chile."},
    {"year": "2014", "title": "Recognition for the official selection of the short film 'Urban Embroidery' at the 1st Mexico Textile Festival, National Autonomous University of Mexico (UNAM)."},
    {"year": "2006", "title": "First place in the 3rd Guatemalan Carpets Competition, Cultural Corporation of the Municipality of Viña del Mar, Chile."},
]

exhibitions = [
    {"year": "2025", "title": "Group exhibition 'Ancestral Pottery', Laguna de Tagua Tagua School Museum, San Vicente de Tagua Tagua, Chile."},
    {"year": "2024", "title": "Group exhibition 'Art Santiago 2024', Gabriela Mistral Cultural Center (GAM), Santiago, Chile."},
    {"year": "2023", "title": "Graduation group exhibition 'Pieza Única', AIEP Professional Institute, Santiago, Chile."},
    {"year": "2023", "title": "Group exhibition 'Bordado Atacameño de la Memoria', Algarrobo Community Center, San Pedro de Atacama and SQM Corporate Building, Santiago, Chile."},
    {"year": "2023", "title": "Group exhibition 'Craft Memories', UNAR, Regional Museum of Rancagua and Museum of Decorative Arts, Santiago, Chile."},
    {"year": "2022", "title": "Group exhibition 'Crafts for Violeta', UNAR, Nemesio Antúnez Gallery UMCE, Santiago, Chile."},
    {"year": "2021", "title": "Group exhibition 'Crafts in Pandemic: A Piece for the Seal of Excellence', UNAR, Montecarmelo Cultural Center, Santiago, Chile."},
    {"year": "2018", "title": "Solo exhibition 'Textiles and Pottery of Tagua Tagua', Dunedin School of Art, Otago Polytechnic, New Zealand."},
    {"year": "2016-2018", "title": "Solo traveling exhibition 'Widufe Kuyfiche – Ancestral Potter', cultural centers in San Vicente de Tagua Tagua, San Fernando, Chépica, Santa Cruz, Rengo, Pichilemu, Lolol, Machalí, Codegua, and Pichidegua."},
    {"year": "2015", "title": "Group exhibition '2nd Ibero-American Crafts Fair', Palacio de La Moneda Cultural Center, Santiago, Chile."},
    {"year": "2015", "title": "Group exhibition 'Expo Cachapoal', Plaza de los Héroes, Rancagua (Copa América 2015), Chile."},
    {"year": "2012", "title": "Solo exhibition 'Retrospective', CODELCO Building Hall, Calama, Chile."},
    {"year": "2012", "title": "Group exhibition 'Ckoitchi', Pablo Neruda Art Gallery, Calama, Chile."},
    {"year": "2011", "title": "Group exhibition 'Color in Winter', Municipal Cultural Corporation of Valparaíso, Chile."},
    {"year": "2010", "title": "Group exhibition 'El Litoral Vive', Cultural Centers in Oberá, Puerto Rico, and Posadas, Misiones, Argentina."},
    {"year": "2008", "title": "Solo exhibition 'Between Chile and Mexico', Contemporary Art Gallery, Casa de la Cultura of Rancagua, Chile."},
    {"year": "2006", "title": "Solo exhibition 'Regional Rock Art on Batik and Shibori Tapestries', Casa de la Cultura of Rancagua, Lircunlauta Museum of San Fernando, and Agustín Ross Cultural Center of Pichilemu, Chile."},
    {"year": "2005", "title": "Solo exhibition 'Reserving Color', Cachapoal Provincial Government, Rancagua, Chile."},
    {"year": "2002", "title": "Group exhibition 'Petroglyphs of the Cipreses River and Man', SITIARTE, Rancagua, Chile."},
    {"year": "2001", "title": "Group exhibition 'Batik Art', Municipal Cultural Corporation of Valdivia, Chile."},
]

about_page = {
    "title": "About Max",
    "description": "Biography, career, and artistic approach of Max Sepúlveda, Chilean visual artist, artisan, and cultural manager. Over 20 years of experience in collaborative art, ceramics, and textiles.",
    "blocks": [
        {
            "type": "text_section",
            "title": "Biography",
            "content": "<p><strong>Max Sepúlveda was born in 1974 in San Vicente de Tagua Tagua, Chile.</strong></p><p>He has developed an extensive creative and productive career in traditional crafts including <strong>pottery, ceramics, and textiles</strong>, reinterpreting pre-Columbian design through a contemporary perspective and experimenting with cross-technique fusions. His inspiration springs from the territories and communities where he creates his individual artworks, knowledge-sharing workshops, and collaborative art projects born out of community dialogue: the artist and community reflect on their identity, memory, natural and cultural heritage, conflicts, scarcity, and everyday abundance. From that affectionate communal encounter, he co-creates artworks that bring these themes to light as a primary source of inspiration.</p><p>The artist envisions the crafts he shares and collaborative community art as powerful <strong>tools for social and personal transformation</strong>. Through diverse artistic processes, Max fosters awareness regarding the importance of social organization, empowerment, mutual support networks, self-critique, and collective evaluation of challenges and successes to contribute to a better quality of life.</p><p>His training took place alongside <strong>master artisans and visual artists throughout Latin America</strong>. He is a Professional Technician in Art and Cultural Management from AIEP Institute (Universidad Andrés Bello, Santiago, Chile), completed a Diploma in Pedagogical Training for Artisans at Universidad Metropolitana de Ciencias de la Educación (UMCE, Santiago, Chile), and completed an internship in Textile Art at the <strong>Universidad Iberoamericana in Mexico City</strong>, among other studies.</p>",
            "image": "assets/images/max-sepulveda-retrato.png",
            "image_position": "right",
            "image_alt": "Portrait of Max Sepúlveda",
            "variant": "portrait-reference",
        },
        {
            "type": "contact",
            "title": "Contact",
            "text": "Contact Max to commission services, collaborations, and volunteer opportunities.",
            "email": "maxsepulvedaz@gmail.com",
            "phone": "+56 9 8654 5810",
            "phone_link": "+56986545810",
            "resume": {"label": "Full CV (PDF)", "url": "assets/pdf/curriculum-max-sepulveda-en.pdf"},
            "social_links": [
                {"platform": "instagram", "label": "Max Sepúlveda on Instagram", "url": "https://www.instagram.com/maxartepopular/"},
                {"platform": "facebook", "label": "Max Sepúlveda on Facebook", "url": "https://www.facebook.com/MaxArteVisual/"},
                {"platform": "youtube", "label": "Max Sepúlveda on YouTube", "url": "https://www.youtube.com/@Warisdey1974"},
            ],
            "variant": "default",
        },
        {
            "type": "dated_list",
            "title": "Awards & Recognitions",
            "subtitle": "Institutional recognitions and notable selections.",
            "items": awards,
        },
        {
            "type": "dated_list",
            "title": "Exhibitions",
            "subtitle": "Chronological selection of solo and group exhibitions.",
            "items": exhibitions,
        },
    ],
}

home_blocks = [
    {
        "type": "hero",
        "title": "Max Sepúlveda",
        "subtitle": "Visual artist, artisan, and cultural manager.",
        "variant": "portada",
    },
    {
        "type": "discipline_showcase",
        "show_header": False,
    },
    {
        "type": "contact",
        "title": "Contact",
        "text": "Get in touch to commission services, workshops, collaborations, and projects.",
        "email": "maxsepulvedaz@gmail.com",
        "phone": "+56 9 8654 5810",
        "phone_link": "+56986545810",
        "resume": {"label": "Full CV (PDF)", "url": "assets/pdf/curriculum-max-sepulveda-en.pdf"},
        "social_links": [
            {"platform": "instagram", "url": "https://www.instagram.com/maxartepopular/", "label": "Instagram"},
            {"platform": "facebook", "url": "https://www.facebook.com/MaxArteVisual/", "label": "Facebook"},
            {"platform": "youtube", "url": "https://www.youtube.com/@Warisdey1974", "label": "YouTube"},
        ],
        "variant": "default",
    },
]
