site = {
    "name": "Max Sepúlveda",
    "title_suffix": "Portfolio",
    "description": "Portfolio profesional de Max Sepúlveda, artista visual, artesano y gestor cultural chileno. Más de 20 años de trayectoria en arte colaborativo, cerámica y textiles.",
    "tagline": "Artista visual · Artesano · Gestor cultural",
    "email": "maxsepulvedaz@gmail.com",
    "phone": "+56 9 8654 5810",
    "phone_link": "+56986545810",
    "location": "San Vicente de Tagua Tagua, Chile",
    "year": "2026",
    "website": "https://maxsepulvedaartevisual.com",
    "instagram": "https://www.instagram.com/maxartepopular/",
    "facebook": "https://www.facebook.com/MaxArteVisual/",
    "youtube": "https://www.youtube.com/@Warisdey1974",
}


def gallery(folder: str, names: list[str]) -> list[str]:
    return [f"assets/images/gallery/{folder}/{name}" for name in names]

disciplines = [
    {
        "name": "Alfarería",
        "description": "Creación de piezas utilitarias y decorativas con técnicas y diseños ancestrales.",
        "icon": "pottery",
        "image": "assets/images/disciplinas/alfareria.jpeg",
        "anchor": "alfareria",
        "panel": "fullbleed",
    },
    {
        "name": "Cerámica",
        "description": "Técnica de moldes, modelado, esgrafiado, uso de engobes y vidriados. Exploración de formas tradicionales con una mirada contemporánea.",
        "icon": "ceramic",
        "image": "assets/images/disciplinas/ceramica.jpeg",
        "anchor": "ceramica",
        "panel": "fullbleed",
    },
    {
        "name": "Bordado",
        "description": "Exploración con 15 puntadas tradicionales.",
        "icon": "embroidery",
        "image": "assets/images/disciplinas/bordado.jpeg",
        "anchor": "bordado",
        "panel": "fullbleed",
    },
    {
        "name": "Batik y bordado",
        "description": "Fusión contemporánea de batik y bordado para poner en valor el patrimonio natural y cultural.",
        "icon": "batik",
        "image": "assets/images/disciplinas/batik-y-bordado.jpeg",
        "anchor": "batik-y-bordado",
        "panel": "fullbleed",
    },
    {
        "name": "Tejidos",
        "description": "Telar mapuche, telar de peine, telar cuadrado, telar artístico, cordonería andina y joyería textil.",
        "icon": "weaving",
        "image": "assets/images/disciplinas/tejidos.jpeg",
        "anchor": "tejidos",
        "panel": "fullbleed",
    },
    {
        "name": "Lanigrafía",
        "description": "Técnica de pegado de lanas y cordones sobre superficies de madera o cartón.",
        "icon": "weaving",
        "image": "assets/images/disciplinas/lanigrafia.jpeg",
        "anchor": "lanigrafia",
        "panel": "fullbleed",
    },
    {
        "name": "Técnicas de teñido por reserva",
        "description": "Batik, pintura en seda y teñido por amarras. Diseños precolombinos y contemporáneos.",
        "icon": "batik",
        "image": "assets/images/disciplinas/tecnicas-de-tenido-por-reserva.jpeg",
        "anchor": "tecnicas-de-tenido-por-reserva",
        "panel": "fullbleed",
    },
    {
        "name": "Audiovisuales",
        "description": "Dirección de arte de cortometrajes y documentales de procesos creativos comunitarios.",
        "icon": "video",
        "image": "assets/images/disciplinas/audiovisuales.jpeg",
        "anchor": "audiovisuales",
        "panel": "fullbleed",
    },
    {
        "name": "Arte colaborativo",
        "description": "Bordados de mapas de la memoria, murales de ensamble de bordado y batik, murales de pintura, pasacalles e intervenciones artísticas en el paisaje natural y cultural. El arte colaborativo como medio de participación y transformación social.",
        "icon": "embroidery",
        "image": "assets/images/disciplinas/arte-colaborativo.jpeg",
        "anchor": "arte-colaborativo",
        "panel": "fullbleed",
    },
]

projects = [
    {
        "title": "Bordado Urbano",
        "slug": "bordado-urbano",
        "date": "2012-05-15",
        "summary": "Proyecto colaborativo en Calama (2012): los habitantes bordaron colectivamente un mapa de 3x2 metros con sus sueños, historias y aspiraciones, junto a un documental con músicos, cantautores y bailarines de la ciudad.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-urbano/",
        "tags": ["Arte Comunitario", "Textil", "Calama", "Documental"],
        "image": "assets/images/gallery/bordado-urbano/bordado-urbano-05.jpg",
        "gallery": gallery(
            "bordado-urbano",
            [
                "bordado-urbano-01.jpg",
                "bordado-urbano-02.jpg",
                "bordado-urbano-03.jpg",
                "bordado-urbano-04.jpg",
                "bordado-urbano-05.jpg",
                "bordado-urbano-06.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Un tapiz de sueños colectivos",
                "content": "<p>El <em>Bordado Urbano</em> fue un proyecto colaborativo ejecutado por el artista Max Sepúlveda en la ciudad de <strong>Calama, Chile</strong>, en el año <strong>2012</strong>. Se realizaron intervenciones públicas en donde los participantes bordaron un mapa de <strong>3 x 2 metros</strong> sobre el cual se plasmaron, a través de puntos bordados de colores, los sueños, historias de amor y desamor, aspiraciones, carencias, abundancias, conflictos y el futuro para su ciudad.</p><p>Al mismo tiempo se realizó un <strong>documental</strong> de la experiencia, en donde también participaron bandas de músicos, cantautores y bailarines de Calama.</p><p>La obra colaborativa, bordada por la gente entrevistada, los participantes y el artista textil Max Sepúlveda, se realizó en diversas locaciones de Calama, como las <strong>ferias rotativas, el Paseo Ramírez, el Mercado Modelo, el sector La Cascada, colegios y plazas de la ciudad</strong>: locaciones que fueron el disparador de esta búsqueda identitaria que se inmortalizó a través del lenguaje audiovisual.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Bordado Charrúa de la Memoria",
        "slug": "bordado-charrua-de-la-memoria",
        "date": "2016-11-20",
        "summary": "Proyecto colaborativo de Max Sepúlveda y el colectivo Cine del Cono Sur en cinco balnearios de Rocha, Uruguay (2016), financiado por el Fondo Concursable para la Cultura del MEC.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/bordado-charrua-de-la-memoria/",
        "tags": ["Arte Comunitario", "Textil", "Uruguay", "Premios"],
        "image": "assets/images/proyectos/intervenciones/mx.jpg",
        "gallery": gallery(
            "bordado-charrua",
            [
                "bordado-charrua-01.jpg",
                "bordado-charrua-02.jpg",
                "bordado-charrua-03.jpg",
                "bordado-charrua-04.jpg",
                "bordado-charrua-05.jpg",
                "bordado-charrua-06.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Rescatando la memoria costera",
                "content": "<p>El <em>Bordado Charrúa de la Memoria</em> fue un proyecto colaborativo ejecutado por el artista Max Sepúlveda y el colectivo de <strong>Cine del Cono Sur</strong> en <strong>cinco balnearios de la Provincia de Rocha, Uruguay</strong>, en el año <strong>2016</strong>, gracias a la adjudicación del <strong>Fondo Concursable para la Cultura del Ministerio de Educación y Cultura de Uruguay</strong>.</p><p>Se realizaron intervenciones públicas en donde los participantes bordaron un mapa de <strong>3 x 2 metros</strong> sobre el cual se plasmaron, a través de puntos bordados de colores, su balneario, su pueblo, su comunidad. En este proceso nos contaron sobre los lugares que dejaron huellas en sus vidas, sus historias de amor, aventuras y desventuras, lugares mágicos e identitarios, lo que se perdió, lo que cambiaría y lo que le falta a su entorno, como también los lugares que deben conservarse y protegerse.</p><p>Junto a los participantes de la experiencia se unieron artistas cantautores, músicos y bailarines, quienes apoyaron la narración plasmada a través de un <strong>documental</strong>.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Residencia Artística en Nueva Zelanda",
        "slug": "textiles-y-alfareria-del-tagua-tagua",
        "date": "2018-08-10",
        "summary": "Residencia artística en la Escuela de Arte del Instituto Politécnico de Dunedin, Nueva Zelanda (2018), con exposición individual, taller de alfarería ancestral Tagua Tagua, mediación cultural y publicación en Revista Scope.",
        "featured": True,
        "live_url": "https://maxsepulvedaartevisual.com/portafolio/residencia-artistica-en-nueva-zelanda/",
        "tags": ["Exposición", "Internacional", "Nueva Zelanda", "Cerámica", "Textil"],
        "image": "assets/images/gallery/nueva-zelanda/nueva-zelanda-02.jpg",
        "gallery": gallery(
            "nueva-zelanda",
            [
                "nueva-zelanda-01.jpg",
                "nueva-zelanda-02.jpg",
                "nueva-zelanda-03.jpg",
                "nueva-zelanda-04.jpg",
                "nueva-zelanda-05.jpg",
                "nueva-zelanda-06.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Intercambio Cultural Chile-Nueva Zelanda",
                "content": "<p>En el año <strong>2018</strong> el artista realizó una <strong>residencia artística en la Escuela de Arte del Instituto Politécnico de Dunedin, Nueva Zelanda</strong>, que incluyó una exposición individual llamada <em>Textiles y Alfarería del Tagua Tagua</em>.</p><p>En el estudio cerámico de la misma escuela organizó un <strong>taller de alfarería ancestral con la técnica Tagua Tagua</strong>, dirigido a alumnos, profesores y artistas de la institución. De igual forma, realizó jornadas de <strong>mediación cultural</strong> de sus obras, tanto en la sala de exposiciones como en el Hub del edificio principal de la institución académica.</p><p>Además, publicó un artículo en la <strong>Revista Scope Contemporary Research Topics Art and Design</strong> sobre su experiencia en la residencia artística.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Exposición Widufe Kuyfiche – Alfarero Ancestral",
        "slug": "widufe-kuyfiche-alfarero-ancestral",
        "date": "2016-03-01",
        "summary": "Creación de 22 piezas de alfarería que ponen en valor el método ancestral Tagua Tagua. Proyecto financiado por el Ministerio de las Culturas (2016), itinerante por la Región de O'Higgins y Nueva Zelanda.",
        "featured": True,
        "tags": ["Investigación", "Cerámica", "Alfarería ancestral", "Patrimonio"],
        "image": "assets/images/proyectos/alfareria/DSC05935.JPG",
        "gallery": gallery(
            "alfareria",
            [f"alfareria-{i:02d}.jpg" for i in range(1, 34)],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Hacedores de Greda",
                "content": "<p>En el año <strong>2016</strong>, gracias a la adjudicación de un fondo del <strong>Ministerio de las Culturas, las Artes y el Patrimonio de Chile</strong>, el artista creó y produjo <strong>22 piezas de alfarería</strong> poniendo en valor el método ancestral Tagua Tagua: obras de tipo ornamental y utilitarias inspiradas en la alfarería precolombina regional.</p><p>Las piezas presentan influencias de la cultura <strong>Inca, Mapuche, Diaguita y Atacameña</strong>, de las antiguas culturas <strong>Bato y Llolleo</strong> (300 a. C. - 800 d. C.) y de la posterior cultura <strong>Aconcagua</strong> (900 d. C.).</p><p>La itinerancia de la muestra se realizó en <strong>10 centros culturales de la Región de O'Higgins</strong> durante dos años y, posteriormente, en <strong>Nueva Zelanda</strong>.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Murales Textiles Colaborativos",
        "slug": "murales-textiles-colaborativos",
        "date": "2020-01-15",
        "summary": "Registro fotográfico de murales textiles colaborativos realizados por Max Sepúlveda junto a comunidades locales.",
        "featured": True,
        "tags": ["Arte Comunitario", "Textil", "Muralismo", "Codelco"],
        "image": "assets/images/proyectos/intervenciones/20240703_201741.jpg",
        "gallery": gallery(
            "murales",
            [
                "mural-01.jpg",
                "mural-02.jpg",
                "mural-03.jpg",
                "mural-04.jpg",
                "mural-05.jpg",
                "mural-06.jpg",
                "mural-07.jpg",
                "mural-08.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Murales textiles colaborativos",
                "content": "<p>Registro fotográfico de murales textiles colaborativos realizados por Max Sepúlveda junto a comunidades locales.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Costa Rica Fashion Week 2019",
        "slug": "costa-rica-fashion-week-2019",
        "date": "2019-08-01",
        "summary": "Invitación a exponer sus obras y las de la Cooperativa Textil Tagua Tagua en Costa Rica Fashion Week 2019, con charla, taller de batik y entrevistas a medios.",
        "featured": True,
        "tags": ["Textil", "Moda", "Internacional", "Costa Rica"],
        "image": "assets/images/proyectos/general/stand CRFW.jpg",
        "gallery": gallery(
            "costa-rica-fashion-week",
            [
                "costa-rica-fashion-week-01.jpg",
                "costa-rica-fashion-week-02.jpg",
                "costa-rica-fashion-week-03.jpg",
                "costa-rica-fashion-week-04.jpg",
                "costa-rica-fashion-week-05.jpg",
                "costa-rica-fashion-week-06.jpg",
                "costa-rica-fashion-week-07.jpg",
                "costa-rica-fashion-week-08.jpg",
            ],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Textil, oficio y diseño contemporáneo",
                "content": "<p>El artista fue invitado a <strong>Costa Rica Fashion Week 2019</strong> para exponer sus obras y las obras de la <strong>Cooperativa Textil Tagua Tagua</strong>.</p><p>Durante su participación compartió una charla llamada <em>Intervención Social a través del Arte Textil</em>, impartió un <strong>taller de batik</strong> y realizó una entrevista a los medios de comunicación nacional.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Resultados Taller de Técnicas Textiles en San Vicente de Tagua Tagua",
        "slug": "resultados-taller-tecnicas-textiles-san-vicente",
        "date": "2024-06-15",
        "summary": "Registro fotográfico de los resultados del taller de técnicas textiles dirigido por Max Sepúlveda en San Vicente de Tagua Tagua.",
        "featured": False,
        "tags": ["Taller", "Textil", "Formación"],
        "image": "assets/images/gallery/taller-san-vicente/taller-san-vicente-01.jpg",
        "gallery": gallery(
            "taller-san-vicente",
            [f"taller-san-vicente-{i:02d}.jpg" for i in range(1, 41)],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Resultados del taller",
                "content": "<p>Registro fotográfico de los resultados del <strong>taller de técnicas textiles</strong> dirigido por Max Sepúlveda en <strong>San Vicente de Tagua Tagua</strong>.</p>",
                "variant": "default",
            },
        ],
    },
    {
        "title": "Resultados del Taller de Bordado y batik en San Pedro de Atacama",
        "slug": "resultados-taller-bordado-batik-san-pedro-de-atacama",
        "date": "2023-06-15",
        "summary": "Registro fotográfico de los resultados del taller de bordado y batik dirigido por Max Sepúlveda en San Pedro de Atacama.",
        "featured": False,
        "tags": ["Taller", "Bordado", "Batik"],
        "image": "assets/images/gallery/taller-bordado-batik-san-pedro/taller-bordado-batik-san-pedro-01.jpg",
        "gallery": gallery(
            "taller-bordado-batik-san-pedro",
            [f"taller-bordado-batik-san-pedro-{i:02d}.jpg" for i in range(1, 16)],
        ),
        "content": [
            {
                "type": "text_section",
                "title": "Resultados del taller",
                "content": "<p>Registro fotográfico de los resultados del <strong>taller de bordado y batik</strong> dirigido por Max Sepúlveda en <strong>San Pedro de Atacama</strong>.</p>",
                "variant": "default",
            },
        ],
    },
]

institutions = [
    "SQM",
    "Novandino Litio",
    "Corporación Proloa",
    "Ministerio de las Culturas, las Artes y el Patrimonio de Chile",
    "Ministerio de Educación y Cultura de Uruguay",
    "Colegio Cryptocaria Alba de Peumo",
    "Gobierno Regional de Antofagasta",
    "Fundación de Cultura de San Pedro de Atacama",
    "Museo Violeta Parra",
    "Gobierno Regional de O'Higgins",
    "Municipalidad de Santa Cruz",
    "Municipalidad de San Vicente de Tagua Tagua",
    "Ministerio de Vivienda y Urbanismo de Chile",
    "Escuela Rewe Waldorf de San Vicente de Tagua Tagua",
    "Escuela Alcaman de Doñihue",
    "Escuela de Joyería Joyarte de Valdivia",
    "Instituto de Desarrollo Agropecuario de Chile INDAP",
    "Fundación Pro Desarrollo de la Mujer de Chile PRODEMU",
    "Corporación de Cultura y Turismo de Calama",
    "Codelco Chile",
    "Centro Cultural Daniel Omar Favero y Centro de Desarrollo Sustentable Mamaroja en Argentina",
    "Agrupación Cultural Rapa Nui \"Maohi o Rapa Nui\"",
    "Servicio Nacional de la Mujer de Chile",
    "Municipalidad de Rancagua",
    "Fondo de Solidaridad e Inversión Social FOSIS Chile",
    "Casa Taller Recreo-Arte Textil en Viña del Mar, Chile",
    "Escuela Textil Factoría Violeta",
    "Municipalidad de Oberá, Argentina",
]

collaborations = [
    "Espacio Cultural Leritchitacks de San Pedro de Atacama",
    "Junta de Vigilancia del río Tinguiririca",
    "Editorial Humanos",
    "Museo Regional de Rancagua",
    "Ecositex",
    "Centro Cultural Montecarmelo",
    "Pichilemu TV",
    "Museo de la Educación Gabriela Mistral",
    "Costa Rica Fashion Week",
    "Otago Polytechnic de Nueva Zelanda",
    "Corporación Parque por la Paz de Villa Grimaldi",
    "Museo de Arte y Artesanía de Linares de Chile",
    "TVO San Vicente",
    "Centro Cultural La Moneda de Chile",
    "Instituto San Vicente",
    "Universidad Autónoma de México",
    "Instituto Chileno-Guatemalteco de Cultura",
    "Corporación de Cultura de la Municipalidad de Viña del Mar, Chile",
    "Secretaría de Cultura del Gobierno de México",
    "Corporación Unificada Nacional de Educación Superior de Colombia",
    "Ministerio de Cultura de Costa Rica",
    "Corporación Pro O'Higgins",
    "Corporación Añañuca",
    "Museo Escolar Laguna de Tagua Tagua",
    "Centro Cultural Gabriela Mistral, Santiago",
    "Agrupación Cultural Ayllu Sin Frontera de San Pedro de Atacama",
    "Tejedoras Urbanas Xico de Ciudad de México",
    "Espacio Cultural Gárgola de Santiago",
    "Casona Cultural de Pichidegua",
    "Centro Cultural Nelly Lemus de Antofagasta",
    "Corporación Cultural Municipal de Valdivia",
    "Centro de Salud Familiar de San Vicente de Tagua Tagua",
    "Museo Lircunlauta",
    "Biblioteca Pública de Chépica",
    "Teatro Municipal de Rengo",
    "Centro Cultural Agustín Ross de Pichilemu",
    "Centro Cultural de Lolol",
    "Centro Cultural de Machalí",
    "Centro Cultural de Codegua",
    "Casa de la Cultura de Rancagua",
    "Lollapalooza 2022",
    "Municipalidad de Recoleta",
    "Gobernación Provincial de Cachapoal",
    "Centro Cultural Ojo del Desierto de Calama",
    "Instituto de Investigaciones Arqueológicas y Museo de la Universidad Católica del Norte",
    "Revista Scope Contemporary Research Topics Art and Design de Nueva Zelanda",
]

awards = [
    {"year": "2021", "title": "Seleccionado nacional para el Catálogo Artesanía en Pandemia del Ministerio de las Culturas, las Artes y el Patrimonio de Chile."},
    {"year": "2015", "title": "Reconocimiento al Artesano 2015, Municipalidad de San Vicente de Tagua Tagua, Chile."},
    {"year": "2014", "title": "Reconocimiento por selección del cortometraje \"Bordado Urbano\" en el I Festival de Textiles de México, Universidad Autónoma de México."},
    {"year": "2006", "title": "Primer lugar en el III Concurso de Alfombras Guatemaltecas, Corporación de Cultura de la Municipalidad de Viña del Mar, Chile."},
]

exhibitions = [
    {"year": "2026", "title": "Exposición individual Andino, Espacio Cultural Leritchitacks de San Pedro de Atacama, Chile."},
    {"year": "2025", "title": "Exposición colectiva Alfarería Ancestral, Museo Escolar Laguna de Tagua Tagua, San Vicente de Tagua Tagua, Chile."},
    {"year": "2024", "title": "Exposición colectiva Art Santiago 2024 en el Centro Cultural Gabriela Mistral GAM, Santiago, Chile."},
    {"year": "2023", "title": "Exposición colectiva de egreso Pieza Única, Instituto Profesional AIEP, Santiago, Chile."},
    {"year": "2023", "title": "Exposición colectiva Bordado Atacameño de la Memoria, Sede Comunitaria Algarrobo, San Pedro de Atacama y Edificio Corporativo de la empresa SQM, Santiago, Chile."},
    {"year": "2023", "title": "Exposición colectiva Memorias de la Artesanía, UNAR, Museo Regional de Rancagua y Museo de Artes Decorativas, Santiago, Chile."},
    {"year": "2022", "title": "Exposición colectiva Artesanías para Violeta, UNAR, Sala Nemesio Antúnez UMCE, Santiago, Chile."},
    {"year": "2021", "title": "Exposición colectiva Artesanía en Pandemia, una Pieza Para el Sello de Excelencia, UNAR, Centro Cultural Montecarmelo, Santiago, Chile."},
    {"year": "2018", "title": "Exposición individual Textiles y Alfarería del Tagua Tagua, Escuela de Arte de Dunedin, Otago Polytechnic, Nueva Zelanda."},
    {"year": "2016-2018", "title": "Exposición individual Widufe Kuyfiche - Alfarero Ancestral, centros culturales de San Vicente de Tagua Tagua, San Fernando, Chépica, Santa Cruz, Rengo, Pichilemu, Lolol, Machalí, Codegua y Pichidegua."},
    {"year": "2015", "title": "Exposición colectiva II Feria de Artesanías Iberoamericanas, Centro Cultural Palacio de la Moneda, Santiago, Chile."},
    {"year": "2015", "title": "Exposición colectiva Expo Cachapoal, Plaza de los Héroes de Rancagua, Copa América 2015, Chile."},
    {"year": "2012", "title": "Exposición individual Retrospectiva, Hall del Edificio de CODELCO, Calama, Chile."},
    {"year": "2012", "title": "Exposición colectiva Ckoitchi, Sala de Arte Pablo Neruda de Calama, Chile."},
    {"year": "2011", "title": "Exposición colectiva Ponle Color al Invierno, Corporación Cultural Municipal de Valparaíso, Chile."},
    {"year": "2010", "title": "Exposición colectiva El Litoral Vive, Casas de la Cultura de las ciudades de Oberá, Puerto Rico y Posadas en Misiones, Argentina."},
    {"year": "2008", "title": "Exposición individual Entre Chile y México, Sala de Arte Contemporáneo de la Casa de la Cultura de Rancagua, Chile."},
    {"year": "2006", "title": "Exposición individual Arte Rupestre Regional en Tapices de Batik y Shibori, Casa de la Cultura de Rancagua, Museo Lircunlauta de San Fernando y Centro Cultural Agustín Ross Edwards de Pichilemu, Chile."},
    {"year": "2005", "title": "Exposición individual Reservando el Color, Gobernación Provincial de Cachapoal, Rancagua, Chile."},
    {"year": "2002", "title": "Exposición colectiva Petroglifos del Río Cipreses y El Hombre, SITIARTE, Rancagua, Chile."},
    {"year": "2001", "title": "Exposición colectiva de Batik, Corporación Cultural Municipal de Valdivia, Chile."},
]

about_page = {
    "title": "Sobre Max",
    "description": "Biografía, trayectoria y enfoque artístico de Max Sepúlveda, artista visual, artesano y gestor cultural chileno. Más de 20 años de experiencia en arte colaborativo, cerámica y textiles.",
    "blocks": [
        {
            "type": "text_section",
            "title": "Biografía",
            "content": "<p><strong>Max Sepúlveda nació en 1974 en San Vicente de Tagua Tagua, Chile.</strong></p><p>Posee un vasto trabajo creativo y productivo en los oficios artesanales de <strong>alfarería, cerámica y textiles</strong>, poniendo en valor el diseño precolombino de forma contemporánea y experimentando con la fusión de técnicas. Su inspiración viene de los territorios y comunidades en donde crea sus obras individuales, talleres de transmisión de conocimientos y obras de arte colaborativas que nacen desde el diálogo comunitario: el artista y la comunidad reflexionan sobre su idiosincrasia, la memoria, la identidad, el patrimonio natural y cultural, los conflictos, las carencias y las abundancias de lo cotidiano. Desde ese encuentro comunitario afectivo co-crea obras de arte que visibilizan dichos tópicos como fuente de inspiración.</p><p>El artista concibe los oficios que comparte y al arte comunitario y colaborativo como poderosas <strong>herramientas de transformación social y personal</strong>. A través de los distintos procesos artísticos, Max busca generar conciencia sobre la importancia de la organización social, su empoderamiento, la creación de redes de apoyo, la autocrítica y la evaluación colectiva de errores y aciertos para contribuir a mejorar la calidad de vida.</p><p>Su formación ha sido con <strong>maestros artesanos y artistas visuales latinoamericanos</strong>. Es Técnico Profesional en Arte y Gestión Cultural del Instituto AIEP de la Universidad Andrés Bello de Santiago de Chile, cursó un Diplomado en Formación Pedagógica para Artesanos en la Universidad Metropolitana de Ciencias de la Educación de Santiago de Chile y realizó una Pasantía en Arte Textil en la <strong>Universidad Iberoamericana de Ciudad de México</strong>, entre otros estudios.</p>",
            "image": "assets/images/max-sepulveda-retrato.png",
            "image_position": "right",
            "image_alt": "Retrato de Max Sepúlveda",
            "variant": "portrait-reference",
        },
        {
            "type": "name_list",
            "title": "Empresas, instituciones y organizaciones",
            "subtitle": "Espacios públicos, privados, educativos y comunitarios con los que ha trabajado o colaborado.",
            "items": institutions,
        },
        {
            "type": "name_list",
            "title": "Colaboraciones",
            "subtitle": "Red de espacios culturales, museos, medios, instituciones educativas y comunidades vinculadas a su trayectoria.",
            "items": collaborations,
        },
        {
            "type": "dated_list",
            "title": "Premios y reconocimientos",
            "subtitle": "Reconocimientos institucionales y selecciones relevantes.",
            "items": awards,
        },
        {
            "type": "dated_list",
            "title": "Exposiciones",
            "subtitle": "Selección cronológica de exposiciones individuales y colectivas.",
            "items": exhibitions,
        },
        {
            "type": "portfolio_grid",
            "title": "Proyectos destacados",
            "subtitle": "Una selección de obras y procesos colaborativos representativos de su trayectoria.",
            "show_featured_only": True,
            "max_items": 7,
            "show_link_to_all": True,
            "variant": "default",
        },
        {
            "type": "contact",
            "title": "Contacto",
            "text": "Contacto para contratar sus servicios, colaboraciones y voluntariados.",
            "email": "maxsepulvedaz@gmail.com",
            "phone": "+56 9 8654 5810",
            "phone_link": "+56986545810",
            "resume": {"label": "Currículo completo", "url": "assets/pdf/curriculum-max-sepulveda.pdf"},
            "social_links": [
                {
                    "platform": "instagram",
                    "label": "Instagram de Max Sepúlveda",
                    "url": "https://www.instagram.com/maxartepopular/",
                },
                {
                    "platform": "facebook",
                    "label": "Facebook Max Sepúlveda Artepopular",
                    "url": "https://www.facebook.com/MaxArteVisual/",
                },
                {
                    "platform": "youtube",
                    "label": "YouTube Warisdey1974",
                    "url": "https://www.youtube.com/@Warisdey1974",
                },
            ],
            "variant": "default",
        },
    ],
}

home_blocks = [
    {
        "type": "hero",
        "title": "Max Sepúlveda",
        "subtitle": "Artista visual, artesano y gestor cultural.",
        "variant": "portada",
    },
    {
        "type": "discipline_showcase",
        "show_header": False,
    },
    {
        "type": "contact",
        "title": "Contacto",
        "text": "Contacto para contratar sus servicios, colaboraciones y voluntariados.",
        "email": "maxsepulvedaz@gmail.com",
        "phone": "+56 9 8654 5810",
        "phone_link": "+56986545810",
        "social_links": [
            {"platform": "instagram", "url": "https://www.instagram.com/maxartepopular/", "label": "Instagram"},
            {"platform": "facebook", "url": "https://www.facebook.com/MaxArteVisual/", "label": "Facebook"},
            {"platform": "youtube", "url": "https://www.youtube.com/@Warisdey1974", "label": "YouTube"},
        ],
        "variant": "default",
    },
]
